use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::embedded::{
    EmbeddedFile, config_files, pipeline_files, skill_files, skill_names, template_files,
};
use crate::layout::{Installation, Prune, SkillLevel};
use crate::target::ReleaseTarget;

/// How a deployed copy compares to what this binary carries.
///
/// A byte comparison rather than a version string: the two are one artifact, so "the same" is
/// decidable exactly, and there is no reading in which a copy is merely probably current. A
/// hand edit and a copy left behind by an older release are the same state on purpose — both
/// mean the deployed bytes are not the bytes this binary would render, and both are repaired
/// by the same command.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ArtifactState {
    Current,
    Modified,
    Absent,
    /// Deployed by an earlier release and no longer carried. An agent still loads it and
    /// follows instructions for commands the binary no longer has, which is worse than a
    /// missing file — so it is named here and removed by a deploy.
    Retired,
}

impl ArtifactState {
    pub fn is_current(self) -> bool {
        matches!(self, ArtifactState::Current)
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct DeployedArtifact {
    pub name: String,
    pub path: PathBuf,
    pub state: ArtifactState,
}

/// A group of artifacts at one location, and whether that location holds a deployment at all.
///
/// An absent group is absent, not stale: an install that deliberately took no skills, or a
/// machine with no scheduler and therefore no pipelines, is coherent. Only a group that WAS
/// deployed can be behind, which is what keeps this check from reporting a defect against a
/// choice the user made.
#[derive(Debug, Clone, Serialize)]
pub struct DeployedGroup {
    pub location: PathBuf,
    pub deployed: bool,
    pub artifacts: Vec<DeployedArtifact>,
}

impl DeployedGroup {
    fn absent(location: PathBuf) -> Self {
        Self {
            location,
            deployed: false,
            artifacts: Vec::new(),
        }
    }

    pub fn stale(&self) -> impl Iterator<Item = &DeployedArtifact> {
        self.artifacts.iter().filter(|a| !a.state.is_current())
    }
}

/// What `<wiki>/AGENTS.md` says generated it.
///
/// The page is the contract every skill reads, and it is rendered from this binary's page
/// format table and the user's config — so a binary that gained a format and did not rewrite
/// it leaves every skill reading a contract that predates it, silently. Nothing rejects that
/// the way the vault rejects a broken link, which is why the page has to declare its generator
/// and this has to compare it.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "state", rename_all = "kebab-case")]
pub enum SchemaState {
    /// No vault is configured, so there is no contract to be behind.
    Unconfigured,
    Missing {
        path: PathBuf,
    },
    /// Present, and generated by another version — or by one old enough not to have said.
    Stale {
        path: PathBuf,
        generator: Option<String>,
    },
    Current {
        path: PathBuf,
    },
}

impl SchemaState {
    pub fn is_current(&self) -> bool {
        matches!(
            self,
            SchemaState::Unconfigured | SchemaState::Current { .. }
        )
    }

    /// Read `path` and decide against `expected`, the generator line this binary writes.
    pub fn read(path: &Path, expected: &str) -> Self {
        let Ok(body) = std::fs::read_to_string(path) else {
            return SchemaState::Missing {
                path: path.to_path_buf(),
            };
        };
        let generator = declared_generator(&body);
        if generator.as_deref() == Some(expected) {
            SchemaState::Current {
                path: path.to_path_buf(),
            }
        } else {
            SchemaState::Stale {
                path: path.to_path_buf(),
                generator,
            }
        }
    }
}

/// The `generator:` key of a page's frontmatter.
///
/// Read from the frontmatter block alone rather than from the document, so a body that quotes
/// the key — the generated page documents its own frontmatter — cannot answer for it.
fn declared_generator(page: &str) -> Option<String> {
    let body = page.strip_prefix("---\n")?;
    let frontmatter = body.split("\n---").next()?;
    let key = format!("{}:", lk_core::frontmatter::field::GENERATOR);
    frontmatter
        .lines()
        .find_map(|line| line.strip_prefix(key.as_str()))
        .map(|value| value.trim().trim_matches('"').to_string())
}

/// Whether this installation is the one this binary would deploy.
#[derive(Debug, Clone, Serialize)]
pub struct InstallationReport {
    pub version: String,
    pub binary: PathBuf,
    /// The release archive this platform installs from, or `None` where the release publishes
    /// none — a source build on an unlisted platform, which is coherent but cannot self-update.
    pub target: Option<String>,
    pub self_replaceable: bool,
    pub skills: Vec<(String, DeployedGroup)>,
    pub pipelines: DeployedGroup,
    pub templates: DeployedGroup,
    pub config: DeployedGroup,
    pub schema: SchemaState,
}

impl InstallationReport {
    /// Compare every deployed copy to what this binary carries.
    ///
    /// `schema` is passed in rather than resolved here: which page is the contract depends on
    /// the vault the config names, and this crate knows nothing about vaults.
    pub fn build(installation: &Installation, schema: SchemaState) -> Self {
        let target = ReleaseTarget::current();
        let skills = installation
            .deployed_skill_levels()
            .into_iter()
            .filter_map(|level: SkillLevel| {
                let root = installation.skills_dir(level)?;
                let prune = Prune::for_level(level);
                let mut artifacts: Vec<DeployedArtifact> = skill_names()
                    .into_iter()
                    .map(|name| {
                        let path = root.join(name);
                        DeployedArtifact {
                            state: compare_tree(&path, &skill_files(name), prune),
                            name: name.to_string(),
                            path,
                        }
                    })
                    .collect();
                artifacts.extend(
                    installation
                        .retired_skills(level)
                        .into_iter()
                        .filter(|_| prune.sweeps())
                        .map(|path| DeployedArtifact {
                            name: path
                                .file_name()
                                .map(|name| name.to_string_lossy().into_owned())
                                .unwrap_or_default(),
                            path,
                            state: ArtifactState::Retired,
                        }),
                );
                Some((
                    level.as_str().to_string(),
                    DeployedGroup {
                        location: root,
                        deployed: true,
                        artifacts,
                    },
                ))
            })
            .collect();

        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            binary: installation.binary().to_path_buf(),
            target: target.map(|t| t.triple.to_string()),
            self_replaceable: target.is_some_and(ReleaseTarget::is_self_replaceable),
            skills,
            pipelines: group(&installation.pipelines_dir(), &pipeline_files()),
            templates: group(&installation.templates_dir(), &template_files()),
            config: group(installation.config_dir(), &config_files()),
            schema,
        }
    }

    /// Everything this binary would rewrite. Destructured so a group added to the report does
    /// not compile until it is counted — the number here is what a caller's exit code and
    /// summary line are derived from, and a new field would otherwise satisfy both silently.
    /// The command that repairs what differs.
    ///
    /// `lore self deploy` rewrites every copy, the schema included — but the schema is the one
    /// artifact inside the user's VAULT, and a deploy writes it best-effort: a drive not mounted
    /// or a wiki directory it cannot reach is a warning, not a failed install. So where the
    /// schema is the only difference, the command that OWNS it is what answers for it, which is
    /// also the error that says why when the vault is the problem. Asked here rather than at
    /// each front door, because `lore status` and `lore self status` naming different repairs
    /// for one report is the disagreement a reader has no way to settle.
    pub fn repair(&self) -> &'static str {
        if self.stale() == 1 && !self.schema.is_current() {
            "lore schema"
        } else {
            "lore self deploy"
        }
    }

    pub fn stale(&self) -> usize {
        let Self {
            version: _,
            binary: _,
            target: _,
            self_replaceable: _,
            skills,
            pipelines,
            templates,
            config,
            schema,
        } = self;
        skills
            .iter()
            .map(|(_, group)| group.stale().count())
            .sum::<usize>()
            + pipelines.stale().count()
            + templates.stale().count()
            + config.stale().count()
            + usize::from(!schema.is_current())
    }
}

/// A group is deployed when at least one file it carries is present.
///
/// Not when the DIRECTORY exists: the config directory exists because the user's own
/// `config.yaml` lives in it, which says nothing about whether the example was ever deployed —
/// so a coherent source build that never ran `self deploy` reported drift it could not have
/// caused. The same rule makes an empty pipelines directory absent rather than wholly stale.
fn group(dir: &Path, files: &[EmbeddedFile]) -> DeployedGroup {
    if !files.iter().any(|file| dir.join(file.relative).exists()) {
        return DeployedGroup::absent(dir.to_path_buf());
    }
    DeployedGroup {
        location: dir.to_path_buf(),
        deployed: true,
        artifacts: files
            .iter()
            .map(|file| {
                let path = dir.join(file.relative);
                DeployedArtifact {
                    name: file.relative.to_string(),
                    state: compare_file(&path, file),
                    path,
                }
            })
            .collect(),
    }
}

/// A deployed file is current when its BYTES and its MODE are the ones this binary carries.
///
/// The mode is part of the artifact, not of the writing: a scheduler executes a pipeline rather
/// than reading it, so a copy that lost its executable bit fails every night while a check that
/// compared only bytes reports the installation healthy and never names the repair.
fn compare_file(path: &Path, file: &EmbeddedFile) -> ArtifactState {
    let Ok(found) = std::fs::read(path) else {
        return ArtifactState::Absent;
    };
    // A symlink at a carried path is not the file a deploy wrote, whatever it resolves to.
    if std::fs::symlink_metadata(path).is_ok_and(|meta| meta.file_type().is_symlink()) {
        return ArtifactState::Modified;
    }
    if found != file.contents.as_bytes() || !mode_matches(path, file.mode) {
        return ArtifactState::Modified;
    }
    ArtifactState::Current
}

/// The one thing the mode is FOR: a scheduler executes a pipeline rather than reading it, so a
/// copy that lost its executable bit fails every night while a byte-only check reports the
/// installation healthy.
///
/// The execute bit and nothing else. Comparing the full mode would report permanent drift on a
/// volume that carries no Unix permissions — an SMB or exFAT `XDG_DATA_HOME` synthesizes one —
/// and `self deploy` could not clear it, which is the unrepairable-drift shape rather than a
/// finding. A synthesized mode still carries execute, so the property that matters survives.
#[cfg(unix)]
fn mode_matches(path: &Path, expected: u32) -> bool {
    use std::os::unix::fs::PermissionsExt;
    if expected & 0o111 == 0 {
        return true;
    }
    std::fs::metadata(path)
        .map(|meta| meta.permissions().mode() & 0o111 != 0)
        .unwrap_or(false)
}

/// Windows carries no such bit, so there is nothing here that could differ.
#[cfg(not(unix))]
fn mode_matches(_path: &Path, _expected: u32) -> bool {
    true
}

/// A tree is current when it holds exactly the files carried for it, byte for byte.
///
/// Exact in both directions: an extra file is a difference too. A reference file a release
/// dropped stays loadable by an agent that was told the directory is the contract, so leaving
/// it uncounted would report a skill as current while it still carries instructions for a
/// binary that is gone.
fn compare_tree(dir: &Path, files: &[EmbeddedFile], prune: Prune) -> ArtifactState {
    if !dir.is_dir() {
        return ArtifactState::Absent;
    }
    for file in files {
        if compare_file(&dir.join(file.relative), file) != ArtifactState::Current {
            return ArtifactState::Modified;
        }
    }
    // A level the deploy does not sweep is judged on what it writes and nothing else. Counting
    // a file there would report drift whose named repair declines to remove it, and the file it
    // would name is exactly the one the project level exists to protect.
    if !prune.sweeps() {
        return ArtifactState::Current;
    }

    // The same comparison the prune uses, for the same reason: a rename onto an entry
    // differing only in case keeps that entry's spelling, so a path comparison here would count
    // the file the deploy correctly KEPT as an extra — reporting drift forever while naming a
    // repair that cannot remove it. The two are one rule and must not be two.
    let expected: std::collections::BTreeSet<crate::layout::FileIdentity> = files
        .iter()
        .map(|file| crate::layout::identity(&dir.join(file.relative)))
        .collect();
    for entry in walkdir::WalkDir::new(dir).into_iter().flatten() {
        // Everything that is not a directory, symlinks included: a link an agent can load is a
        // file to that agent, and `walkdir` does not follow one.
        if !entry.file_type().is_dir() && !expected.contains(&crate::layout::identity(entry.path()))
        {
            return ArtifactState::Modified;
        }
    }
    ArtifactState::Current
}

#[cfg(test)]
mod tests {
    /// Every case below is about a level the deploy SWEEPS; the one that does not is pinned by
    /// `a_level_the_deploy_leaves_alone_is_judged_on_what_it_writes`.
    fn compare_tree_sweeping(dir: &Path, files: &[EmbeddedFile]) -> ArtifactState {
        compare_tree(dir, files, Prune::Sweep)
    }

    use super::*;

    fn file(relative: &'static str, contents: &'static str) -> EmbeddedFile {
        EmbeddedFile {
            relative,
            contents,
            mode: 0o644,
        }
    }

    /// The tree comparison writes its fixtures with `write_atomic`, which stamps the mode the
    /// artifact declares — the same writer a deploy uses, so the fixtures are the real thing.
    fn place(dir: &std::path::Path, files: &[EmbeddedFile]) {
        for file in files {
            let path = dir.join(file.relative);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            lk_core::fs::write_atomic(&path, file.contents.as_bytes(), Some(file.mode)).unwrap();
        }
    }

    #[test]
    fn a_directory_that_was_never_deployed_is_absent_not_stale() {
        let tmp = tempfile::tempdir().unwrap();
        let group = group(&tmp.path().join("pipelines"), &pipeline_files());
        assert!(!group.deployed);
        assert_eq!(group.stale().count(), 0);
    }

    #[test]
    fn a_matching_tree_is_current() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("skill");
        std::fs::create_dir_all(dir.join("references")).unwrap();
        std::fs::write(dir.join("SKILL.md"), "skill").unwrap();
        std::fs::write(dir.join("references/a.md"), "ref").unwrap();
        assert_eq!(
            compare_tree_sweeping(
                &dir,
                &[file("SKILL.md", "skill"), file("references/a.md", "ref")]
            ),
            ArtifactState::Current
        );
    }

    #[test]
    fn an_edited_file_makes_the_tree_modified() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("skill");
        place(&dir, &[file("SKILL.md", "hand edited")]);
        assert_eq!(
            compare_tree_sweeping(&dir, &[file("SKILL.md", "skill")]),
            ArtifactState::Modified
        );
    }

    /// A file a release dropped still loads for an agent told the directory is the contract.
    #[test]
    fn a_file_the_set_no_longer_holds_makes_the_tree_modified() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("skill");
        place(
            &dir,
            &[
                file("SKILL.md", "skill"),
                file("references/old.md", "superseded"),
            ],
        );
        assert_eq!(
            compare_tree_sweeping(&dir, &[file("SKILL.md", "skill")]),
            ArtifactState::Modified
        );
    }

    /// A pipeline is fired by a scheduler, which executes it. A copy that lost its bit fails
    /// every night while a byte-only check reports the installation healthy.
    #[cfg(unix)]
    #[test]
    fn a_file_that_lost_its_executable_bit_is_not_current() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("pipelines");
        std::fs::create_dir_all(&dir).unwrap();
        let carried = EmbeddedFile {
            relative: "lore-daily.sh",
            contents: "#!/usr/bin/env bash\n",
            mode: 0o755,
        };
        let path = dir.join(carried.relative);
        std::fs::write(&path, carried.contents).unwrap();

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).unwrap();
        assert_eq!(compare_file(&path, &carried), ArtifactState::Current);

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert_eq!(
            compare_file(&path, &carried),
            ArtifactState::Modified,
            "identical bytes are not enough when the bit is what runs it"
        );
    }

    /// The check and the prune are one rule. While they were two, the file `write_tree`
    /// The check and the prune are one rule. At the project level the deploy writes what this
    /// binary carries and removes nothing, because a checkout's tracked files can be on the
    /// other end — so an extra file there is not drift, and reporting it would name a repair
    /// that declines to perform it.
    #[test]
    fn a_level_the_deploy_leaves_alone_is_judged_on_what_it_writes() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("lore-ingest");
        let carried = [file("SKILL.md", "skill")];
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("SKILL.md"), "skill").unwrap();
        std::fs::write(dir.join("NOTES.md"), "the team's own").unwrap();

        assert_eq!(
            compare_tree(&dir, &carried, Prune::Leave),
            ArtifactState::Current
        );
        assert_eq!(
            compare_tree(&dir, &carried, Prune::Sweep),
            ArtifactState::Modified
        );

        // What it DOES carry is still judged there.
        std::fs::write(dir.join("SKILL.md"), "edited").unwrap();
        assert_eq!(
            compare_tree(&dir, &carried, Prune::Leave),
            ArtifactState::Modified
        );
    }

    /// correctly kept on a case-folding volume was what `compare_tree` counted as an extra —
    /// drift reported forever, with a repair that could not remove it.
    #[cfg(unix)]
    #[test]
    fn the_check_counts_what_the_prune_keeps() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("skill");
        let carried = [file("SKILL.md", "skill")];
        crate::layout::write_tree_for_tests(&dir, &carried).unwrap();
        assert_eq!(
            compare_tree_sweeping(&dir, &carried),
            ArtifactState::Current
        );

        std::os::unix::fs::symlink("SKILL.md", dir.join("EXTRA.md")).unwrap();
        assert_eq!(
            compare_tree_sweeping(&dir, &carried),
            ArtifactState::Modified,
            "a link an agent can load is a file the check has to see"
        );
    }

    #[test]
    fn the_generator_is_read_from_the_frontmatter_it_declares() {
        let page = "---\ntype: schema\ngenerator: lore 0.20.0\n---\n\n# Formats\n";
        assert_eq!(declared_generator(page).as_deref(), Some("lore 0.20.0"));
    }

    /// The generated page documents its own frontmatter keys, so the word appears in the body
    /// of every copy. Reading the document rather than the block would answer from the prose.
    #[test]
    fn a_generator_named_in_the_body_does_not_answer_for_the_page() {
        let page = "---\ntype: schema\n---\n\n| generator: lore 9.9.9 | a frontmatter key |\n";
        assert_eq!(declared_generator(page), None);
    }

    /// One report, one repair. `lore status` and `lore self status` read the same report, and
    /// naming different commands for it is a disagreement a reader has no way to settle.
    #[test]
    fn the_schema_alone_names_the_command_that_owns_it() {
        let tmp = tempfile::tempdir().unwrap();
        let installation = Installation::at(
            tmp.path().join("bin/lore"),
            tmp.path().join("data"),
            tmp.path().join("config"),
            Some(tmp.path().join("home")),
            None,
        );

        // Nothing is deployed under this installation, so the schema is the only thing that
        // can differ.
        let only_schema = InstallationReport::build(
            &installation,
            SchemaState::Missing {
                path: tmp.path().join("AGENTS.md"),
            },
        );
        assert_eq!(only_schema.stale(), 1);
        assert_eq!(only_schema.repair(), "lore schema");

        let nothing_differs = InstallationReport::build(&installation, SchemaState::Unconfigured);
        assert_eq!(nothing_differs.stale(), 0);
        assert_eq!(nothing_differs.repair(), "lore self deploy");
    }

    #[test]
    fn a_page_that_declares_no_generator_is_stale() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("AGENTS.md");
        std::fs::write(&path, "---\ntype: schema\n---\n").unwrap();
        assert!(matches!(
            SchemaState::read(&path, "lore 0.20.0"),
            SchemaState::Stale {
                generator: None,
                ..
            }
        ));
    }

    #[test]
    fn a_page_generated_by_this_version_is_current() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("AGENTS.md");
        std::fs::write(&path, "---\ntype: schema\ngenerator: lore 0.20.0\n---\n").unwrap();
        assert!(SchemaState::read(&path, "lore 0.20.0").is_current());
        assert!(!SchemaState::read(&path, "lore 0.21.0").is_current());
    }

    #[test]
    fn an_unconfigured_vault_has_no_contract_to_be_behind() {
        assert!(SchemaState::Unconfigured.is_current());
    }
}
