use std::path::{Path, PathBuf};

use crate::config::VaultDirs;

/// The wiki meta-pages Lorekeeper generates: the catalog (`lore wiki index`), the page-format
/// schema (`lore schema`), the knowledge timeline (`lore wiki log`) and the citation-cluster
/// navigation map (`lore wiki map`).
///
/// Named here and used at every write and read site rather than spelled inline, like the
/// subdirectory names below. [`RESERVED_WIKI_FILES`] is built from them, so renaming one cannot
/// leave the graph excluding a name nothing writes while treating the new one as a knowledge
/// page — which would put a generated file in the catalog, in the analysis graph, and in orphan
/// and index-drift findings.
pub const INDEX_FILE: &str = "index.md";
pub const SCHEMA_FILE: &str = "AGENTS.md";
pub const TIMELINE_FILE: &str = "log.md";
pub const MAP_FILE: &str = "map.md";

/// Reserved wiki meta-page filenames generated by Lorekeeper itself. They are not knowledge
/// pages. Single-sourced here so the index builder (`lk-vault`) and the graph (`lk-graph`)
/// agree on what to exclude from the catalog, the analysis graph, and orphan / index-drift
/// findings.
pub const RESERVED_WIKI_FILES: [&str; 4] = [INDEX_FILE, SCHEMA_FILE, TIMELINE_FILE, MAP_FILE];

/// The `type` the citation-cluster navigation map and the page-format schema declare. Named
/// here rather than written inline at the two render sites, so the value a page carries and the
/// value [`PAGE_FORMATS`] admits cannot drift apart. The catalog and the timeline declare no
/// `type`; they are pure listings of pages that carry their own.
pub const MAP_FORMAT: &str = "map";
pub const SCHEMA_FORMAT: &str = "schema";

/// Every value the `type` frontmatter key takes on a page this tool writes — the page-format
/// ids `lore schema` publishes, and OKF's one required key.
///
/// A page therefore states its own provenance, which is what lets a directory be recognized as
/// holding Lorekeeper's output rather than someone's own notes without guessing at content. The
/// personal-module formats are included: whether they are PRODUCED depends on config, but a
/// page carrying one was still written here. So are the two generated wiki meta-pages, which
/// are the only Lorekeeper output a wiki directory holding no concepts yet can be recognized by.
pub const PAGE_FORMATS: [&str; 12] = [
    "concept",
    "daily",
    "document",
    "exploration",
    "weekly-synthesis",
    "work-log",
    "weekly-review",
    "monthly-review",
    "quarterly-review",
    "annual-review",
    MAP_FORMAT,
    SCHEMA_FORMAT,
];

/// Fixed subdirectory names within the configurable top-level vault dirs. The
/// top-level dirs (`<daily>`, `<personal>`, `<synthesis>`, `<wiki>`) are user-set
/// via `vault.dirs.*`; these leaf names are structural and single-sourced here so
/// every crate that builds or scans a vault path agrees on them — never an inline
/// literal.
pub const CONCEPTS_SUBDIR: &str = "concepts";
pub const DOCUMENTS_SUBDIR: &str = "documents";
pub const EXPLORATIONS_SUBDIR: &str = "explorations";
pub const WORK_LOG_SUBDIR: &str = "work-log";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VaultPath(PathBuf);

impl VaultPath {
    pub fn daily(dirs: &VaultDirs, source_id: &str, date: jiff::civil::Date) -> Self {
        Self(
            PathBuf::from(&dirs.daily)
                .join(source_id)
                .join(format!("{date}.md")),
        )
    }

    pub fn work_log(dirs: &VaultDirs, date: jiff::civil::Date) -> Self {
        Self(work_log_dir(dirs).join(format!("{date}.md")))
    }

    pub fn weekly_synthesis(dirs: &VaultDirs, year: i16, week: u8) -> Self {
        Self(
            PathBuf::from(&dirs.synthesis)
                .join(&dirs.weekly)
                .join(format!("{year}-W{week:02}.md")),
        )
    }

    pub fn weekly_review(dirs: &VaultDirs, year: i16, week: u8) -> Self {
        Self(
            PathBuf::from(&dirs.personal)
                .join(&dirs.weekly)
                .join(format!("{year}-W{week:02}.md")),
        )
    }

    pub fn monthly_review(dirs: &VaultDirs, year: i16, month: u8) -> Self {
        Self(
            PathBuf::from(&dirs.personal)
                .join(&dirs.monthly)
                .join(format!("{year}-{month:02}.md")),
        )
    }

    pub fn quarterly_review(dirs: &VaultDirs, year: i16, quarter: u8) -> Self {
        Self(
            PathBuf::from(&dirs.personal)
                .join(&dirs.quarterly)
                .join(format!("{year}-Q{quarter}.md")),
        )
    }

    pub fn annual_review(dirs: &VaultDirs, year: i16) -> Self {
        Self(
            PathBuf::from(&dirs.personal)
                .join(&dirs.annual)
                .join(format!("{year}.md")),
        )
    }

    pub fn concept(dirs: &VaultDirs, slug: &str) -> Self {
        Self(concepts_dir(dirs).join(format!("{slug}.md")))
    }

    pub fn document(dirs: &VaultDirs, slug: &str) -> Self {
        Self(documents_dir(dirs).join(format!("{slug}.md")))
    }

    pub fn exploration(dirs: &VaultDirs, slug: &str) -> Self {
        Self(explorations_dir(dirs).join(format!("{slug}.md")))
    }

    pub fn resolve(&self, vault_root: &Path) -> PathBuf {
        vault_root.join(&self.0)
    }
}

/// Relative directory holding the work-log pages (`<personal>/work-log/`).
pub fn work_log_dir(dirs: &VaultDirs) -> PathBuf {
    PathBuf::from(&dirs.personal).join(WORK_LOG_SUBDIR)
}

/// Relative directory holding the concept pages (`<wiki>/concepts/`).
pub fn concepts_dir(dirs: &VaultDirs) -> PathBuf {
    PathBuf::from(&dirs.wiki).join(CONCEPTS_SUBDIR)
}

/// Relative directory holding the document pages (`<wiki>/documents/`).
pub fn documents_dir(dirs: &VaultDirs) -> PathBuf {
    PathBuf::from(&dirs.wiki).join(DOCUMENTS_SUBDIR)
}

/// Relative directory holding the exploration pages (`<wiki>/explorations/`).
pub fn explorations_dir(dirs: &VaultDirs) -> PathBuf {
    PathBuf::from(&dirs.wiki).join(EXPLORATIONS_SUBDIR)
}

impl AsRef<Path> for VaultPath {
    fn as_ref(&self) -> &Path {
        &self.0
    }
}

impl std::fmt::Display for VaultPath {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0.display())
    }
}

pub fn quarter_of_month(month: u8) -> u8 {
    debug_assert!((1..=12).contains(&month), "month must be 1-12, got {month}");
    (month - 1) / 3 + 1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn daily_path() {
        let dirs = VaultDirs::default();
        let date = jiff::civil::date(2026, 5, 23);
        let path = VaultPath::daily(&dirs, "ai-news", date);
        assert_eq!(path.to_string(), "daily/ai-news/2026-05-23.md");
    }

    #[test]
    fn work_log_path() {
        let dirs = VaultDirs::default();
        let date = jiff::civil::date(2026, 5, 23);
        let path = VaultPath::work_log(&dirs, date);
        assert_eq!(path.to_string(), "me/work-log/2026-05-23.md");
    }

    #[test]
    fn weekly_synthesis_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::weekly_synthesis(&dirs, 2026, 21);
        assert_eq!(path.to_string(), "synthesis/weekly/2026-W21.md");
    }

    #[test]
    fn weekly_review_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::weekly_review(&dirs, 2026, 21);
        assert_eq!(path.to_string(), "me/weekly/2026-W21.md");
    }

    #[test]
    fn monthly_review_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::monthly_review(&dirs, 2026, 5);
        assert_eq!(path.to_string(), "me/monthly/2026-05.md");
    }

    #[test]
    fn quarterly_review_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::quarterly_review(&dirs, 2026, 2);
        assert_eq!(path.to_string(), "me/quarterly/2026-Q2.md");
    }

    #[test]
    fn annual_review_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::annual_review(&dirs, 2026);
        assert_eq!(path.to_string(), "me/annual/2026.md");
    }

    #[test]
    fn concept_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::concept(&dirs, "claude-code");
        assert_eq!(path.to_string(), "wiki/concepts/claude-code.md");
    }

    #[test]
    fn document_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::document(&dirs, "cloud-sql-extensions-report");
        assert_eq!(
            path.to_string(),
            "wiki/documents/cloud-sql-extensions-report.md"
        );
    }

    #[test]
    fn exploration_path() {
        let dirs = VaultDirs::default();
        let path = VaultPath::exploration(&dirs, "api-replay-checklist");
        assert_eq!(
            path.to_string(),
            "wiki/explorations/api-replay-checklist.md"
        );
    }

    #[test]
    fn custom_dirs() {
        let dirs = VaultDirs {
            personal: "my-stuff".into(),
            ..Default::default()
        };
        let date = jiff::civil::date(2026, 5, 23);
        let path = VaultPath::work_log(&dirs, date);
        assert_eq!(path.to_string(), "my-stuff/work-log/2026-05-23.md");
    }

    #[test]
    fn quarter_calculation() {
        assert_eq!(quarter_of_month(1), 1);
        assert_eq!(quarter_of_month(3), 1);
        assert_eq!(quarter_of_month(4), 2);
        assert_eq!(quarter_of_month(6), 2);
        assert_eq!(quarter_of_month(7), 3);
        assert_eq!(quarter_of_month(9), 3);
        assert_eq!(quarter_of_month(10), 4);
        assert_eq!(quarter_of_month(12), 4);
    }
}
