//! Wiki index builder — a deterministic, hierarchical catalog of every vault page.
//!
//! Walks the vault directories (wiki concepts/documents/explorations, daily sources,
//! personal work-log, and synthesis tiers), parses each markdown file's frontmatter via
//! [`lk_core::frontmatter::parse_page`], extracts a first-sentence summary from the page
//! body (see `truncate_summary`), groups entries by category, and renders ONE markdown
//! document — never split into sub-pages, like `log.md`/`map.md`. No LLM, no heuristics —
//! running it twice produces the same bytes.
//!
//! Section labels and heading targets come from [`lk_core::i18n`] so the index honors
//! `vault.locale` like the rest of the pipeline.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use lk_core::config::VaultDirs;
use lk_core::frontmatter::parse_page;
use lk_core::i18n::Locale;
use lk_core::vault_path::{concepts_dir, documents_dir, explorations_dir, work_log_dir};
use walkdir::WalkDir;

use crate::{VaultError, VaultWriter};

/// Build the wiki index body for the vault at `vault_root`, using `locale` to pick
/// section headings and the body-heading targets used by the one-line extractors.
///
/// A single deterministic catalog: every page grouped by category under one `index.md`,
/// each entry a `[[link]] — first-sentence summary`. Like `log.md`/`map.md` it is never
/// split — summaries are bounded to one sentence (see `truncate_summary`), so the catalog
/// stays a scannable one-liner-per-page and grows linearly in node count.
///
/// Returns the rendered markdown (caller writes it). Walks the vault filesystem
/// directly — directories that don't exist are simply skipped (an empty vault yields
/// just the header).
pub fn build_index(
    vault_root: &Path,
    locale: Locale,
    dirs: &VaultDirs,
) -> Result<String, VaultError> {
    let strings = locale.strings();

    let concept_rel = concepts_dir(dirs);
    let concept_rel_str = concept_rel.to_string_lossy().replace('\\', "/");
    let concepts =
        collect_dir_grouped(vault_root, &concept_rel, "category", Some(&concept_rel_str));
    // Group documents by `document_type` — a field EVERY document carries — so the
    // catalog buckets consistently (vs `source_project`, which only some documents have).
    let documents = collect_dir_grouped(vault_root, &documents_dir(dirs), "document_type", None);
    let explorations = collect_dir(vault_root, &explorations_dir(dirs));

    // daily/ holds one sub-directory per source ID. We keep them as separate groups so
    // the index shows pages-per-source counts and stable ordering.
    let mut daily_groups: BTreeMap<String, Vec<IndexEntry>> = BTreeMap::new();
    let daily_root = vault_root.join(&dirs.daily);
    if daily_root.is_dir() {
        let mut sub_dirs: Vec<(String, PathBuf)> = Vec::new();
        for entry in std::fs::read_dir(&daily_root)? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                let name = entry.file_name().to_string_lossy().into_owned();
                sub_dirs.push((name, entry.path()));
            }
        }
        sub_dirs.sort_by(|a, b| a.0.cmp(&b.0));
        for (source_id, dir) in sub_dirs {
            let rel = Path::new(&dirs.daily).join(&source_id);
            let entries = collect_files(&rel, &dir, "category", None);
            if !entries.is_empty() {
                daily_groups.insert(source_id, entries);
            }
        }
    }

    let work_log = collect_dir(vault_root, &work_log_dir(dirs));

    // Synthesis tiers are merged into one bucket so the index has a single "synthesis"
    // section. Each entry keeps its full vault-relative path so the wikilink target is
    // unambiguous.
    let mut synthesis: Vec<IndexEntry> = Vec::new();
    let synthesis_dirs = [
        PathBuf::from(&dirs.synthesis).join(&dirs.weekly),
        PathBuf::from(&dirs.personal).join(&dirs.weekly),
        PathBuf::from(&dirs.personal).join(&dirs.monthly),
        PathBuf::from(&dirs.personal).join(&dirs.quarterly),
        PathBuf::from(&dirs.personal).join(&dirs.annual),
    ];
    for sub in &synthesis_dirs {
        synthesis.extend(collect_dir(vault_root, sub));
    }
    synthesis.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));

    let total = concepts.len()
        + documents.len()
        + explorations.len()
        + daily_groups.values().map(Vec::len).sum::<usize>()
        + work_log.len()
        + synthesis.len();

    let mut out = String::new();
    writeln!(out, "# Wiki Index").unwrap();
    writeln!(out).unwrap();
    // No timestamp: the index is a deterministic function of vault content, so an
    // unchanged vault re-renders byte-identical bytes and a re-run is a true no-op
    // (the daily scheduled rebuild relies on this).
    writeln!(out, "> Generated by `lore wiki index` — {total} pages").unwrap();

    if !concepts.is_empty() {
        render_grouped_section(
            &mut out,
            &concepts,
            |body| extract_across_locales(body, |s| s.concept_synthesis, first_line_under_heading),
            strings.index_concepts,
            strings.uncategorized,
        );
    }

    if !documents.is_empty() {
        render_grouped_section(
            &mut out,
            &documents,
            |body| extract_across_locales(body, |s| s.summary, first_line_under_heading),
            strings.index_documents,
            strings.uncategorized,
        );
    }

    if !explorations.is_empty() {
        render_group(
            &mut out,
            strings.index_explorations,
            explorations.len(),
            &explorations,
            |body| {
                extract_across_locales(body, |s| s.exploration_question, first_line_under_heading)
            },
        );
    }

    for (source_id, entries) in &daily_groups {
        let title = format!("{} — {}", strings.index_daily, source_id);
        render_group(&mut out, &title, entries.len(), entries, |body| {
            extract_across_locales(
                body,
                |s| s.summary,
                |b, h| first_bullet_under_heading(b, h).or_else(|| first_line_under_heading(b, h)),
            )
        });
    }

    if !work_log.is_empty() {
        render_group(
            &mut out,
            strings.index_work_log,
            work_log.len(),
            &work_log,
            |body| {
                extract_across_locales(body, |s| s.topic_summary, first_subheading_under_heading)
            },
        );
    }

    if !synthesis.is_empty() {
        // Synthesis/review pages: extract the NARRATIVE section (weekly themes / key summary /
        // overall summary) across all locales — not the body's first non-heading line, which
        // on a review page is a `## 기간` date or a category-table row, not a summary.
        render_group(
            &mut out,
            strings.index_synthesis,
            synthesis.len(),
            &synthesis,
            |body| {
                extract_across_locales(body, |s| s.key_summary, first_line_under_heading)
                    .or_else(|| {
                        extract_across_locales(
                            body,
                            |s| s.overall_summary,
                            first_line_under_heading,
                        )
                    })
                    .or_else(|| {
                        extract_across_locales(
                            body,
                            |s| s.key_themes_this_week,
                            first_line_under_heading,
                        )
                    })
            },
        );
    }

    Ok(out)
}

/// Run a section extractor against EVERY locale's heading, returning the first hit. An
/// on-disk page authored under a previous `vault.locale` (e.g. `## 핵심` before a ko→en
/// switch) is still found — the READ-tolerates-any-locale invariant the rest of the codebase
/// (`capture_section`/`backlinks`/`audit`/`child_narrative`) follows; only WRITE uses the
/// current locale. `pick` selects the section heading from a locale's strings; `extract`
/// pulls the one-liner from that section's body.
fn extract_across_locales(
    body: &str,
    pick: impl Fn(&'static lk_core::i18n::Strings) -> &'static str,
    extract: impl Fn(&str, &str) -> Option<String>,
) -> Option<String> {
    Locale::ALL
        .iter()
        .find_map(|l| extract(body, pick(l.strings())))
}

/// Build the index and write it atomically to `<vault_root>/<wiki>/index.md`.
///
/// The temp file lives next to the final path so the rename is on the same filesystem
/// and therefore atomic. Returns the absolute path that was written.
pub async fn write_index(
    vault_root: &Path,
    locale: Locale,
    dirs: &VaultDirs,
) -> Result<PathBuf, VaultError> {
    let content = build_index(vault_root, locale, dirs)?;
    let wiki_dir = vault_root.join(&dirs.wiki);
    let main_rel = Path::new(&dirs.wiki).join("index.md");
    VaultWriter::new(vault_root)
        .write_page(&main_rel, &content)
        .await?;
    Ok(wiki_dir.join("index.md"))
}

/// A single catalog entry: vault-relative path, the slug used in the wikilink, and the
/// raw page body (used to extract a per-category one-liner at render time).
struct IndexEntry {
    rel_path: String,
    /// Wikilink target. Daily/work-log/synthesis pages use the full vault-relative
    /// path (without `.md`); concepts use `slug|title` pipe format for correct
    /// resolution by filename while preserving readable display in Obsidian.
    link_target: String,
    body: String,
    category: Option<String>,
}

fn collect_dir(vault_root: &Path, rel: &Path) -> Vec<IndexEntry> {
    collect_dir_grouped(vault_root, rel, "category", None)
}

fn collect_dir_grouped(
    vault_root: &Path,
    rel: &Path,
    group_field: &str,
    concept_rel_dir: Option<&str>,
) -> Vec<IndexEntry> {
    let abs = vault_root.join(rel);
    if !abs.is_dir() {
        return Vec::new();
    }
    collect_files(rel, &abs, group_field, concept_rel_dir)
}

fn collect_files(
    rel_dir: &Path,
    abs_dir: &Path,
    group_field: &str,
    concept_rel_dir: Option<&str>,
) -> Vec<IndexEntry> {
    let mut entries: Vec<IndexEntry> = Vec::new();
    for w in WalkDir::new(abs_dir).follow_links(false) {
        let w = match w {
            Ok(w) => w,
            Err(e) => {
                tracing::warn!(error = %e, dir = %abs_dir.display(), "skipping unreadable path");
                continue;
            }
        };
        if !w.file_type().is_file() {
            continue;
        }
        let path = w.path();
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        // Skip Lorekeeper's reserved meta files (index catalog, timeline, navigation map,
        // AGENTS.md schema) — they are not knowledge pages.
        if let Some(name) = path.file_name().and_then(|n| n.to_str())
            && lk_core::vault_path::RESERVED_WIKI_FILES.contains(&name)
        {
            continue;
        }

        let raw = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!(error = %e, path = %path.display(), "skipping unreadable file");
                continue;
            }
        };
        let page = match parse_page(&raw) {
            Ok(p) => p,
            Err(e) => {
                tracing::warn!(error = %e, path = %path.display(), "skipping malformed frontmatter");
                continue;
            }
        };
        // Files without any frontmatter are skipped — only Lorekeeper-managed pages
        // belong in the index.
        if page.frontmatter.fields.is_empty() {
            continue;
        }

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        // `WalkDir` recurses, so a page may live in a subdirectory of `abs_dir`.
        // Carry that nesting into the vault-relative path (and the wikilink target)
        // instead of flattening every page onto `rel_dir` — otherwise nested pages
        // with the same stem collide and links point at the wrong path.
        let nested = path
            .parent()
            .and_then(|p| p.strip_prefix(abs_dir).ok())
            .filter(|p| !p.as_os_str().is_empty());
        let entry_rel_dir = match nested {
            Some(sub) => rel_dir.join(sub),
            None => rel_dir.to_path_buf(),
        };
        let rel_path = entry_rel_dir.join(format!("{stem}.md"));
        let rel_path = rel_path.to_string_lossy().replace('\\', "/");
        let rel_dir_str = entry_rel_dir.to_string_lossy().replace('\\', "/");

        let link_target = if concept_rel_dir.is_some_and(|c| rel_dir_str == c) {
            let title = page
                .frontmatter
                .get("title")
                .and_then(|v| v.as_str())
                .filter(|s| !s.is_empty() && *s != stem);
            match title {
                Some(t) => format!("{stem}|{t}"),
                None => stem.clone(),
            }
        } else {
            format!("{rel_dir_str}/{stem}")
        };

        let category = page
            .frontmatter
            .get(group_field)
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .map(String::from);

        entries.push(IndexEntry {
            rel_path,
            link_target,
            body: page.body,
            category,
        });
    }
    entries.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));
    entries
}

fn render_group(
    out: &mut String,
    title: &str,
    count: usize,
    entries: &[IndexEntry],
    extract: impl Fn(&str) -> Option<String>,
) {
    writeln!(out).unwrap();
    writeln!(out, "## {title} ({count})").unwrap();
    writeln!(out).unwrap();
    for entry in entries {
        write_entry_line(out, entry, &extract);
    }
}

/// Render a section grouped by category into `### {group}` sub-headings under one
/// `## {section_title}`. Single page — never split — so the catalog stays one file like
/// `log.md`/`map.md`; summaries are bounded by `truncate_summary` to keep each line scannable.
fn render_grouped_section(
    out: &mut String,
    entries: &[IndexEntry],
    extract: impl Fn(&str) -> Option<String>,
    section_title: &str,
    uncategorized_label: &str,
) {
    let mut by_group: BTreeMap<String, Vec<&IndexEntry>> = BTreeMap::new();
    let mut ungrouped: Vec<&IndexEntry> = Vec::new();
    for entry in entries {
        match &entry.category {
            Some(g) => by_group.entry(g.clone()).or_default().push(entry),
            None => ungrouped.push(entry),
        }
    }

    writeln!(out).unwrap();
    writeln!(out, "## {section_title} ({})", entries.len()).unwrap();

    let groups = by_group.iter().map(|(g, e)| (g.as_str(), e)).chain(
        std::iter::once((uncategorized_label, &ungrouped)).filter(|_| !ungrouped.is_empty()),
    );
    for (group, group_entries) in groups {
        writeln!(out).unwrap();
        writeln!(out, "### {group} ({})", group_entries.len()).unwrap();
        writeln!(out).unwrap();
        for entry in group_entries {
            write_entry_line(out, entry, &extract);
        }
    }
}

/// One catalog line: `- [[link]] — first-sentence summary` (or just the link when the
/// page has no extractable summary). The summary is reduced to PLAIN TEXT first
/// (`strip_wikilinks`) so the only `[[…]]` on the line is the entry's own link — a wikilink
/// sitting in a page's summary prose must not read as a second catalog link (it would skew
/// `graph index-sync`).
fn write_entry_line(
    out: &mut String,
    entry: &IndexEntry,
    extract: impl Fn(&str) -> Option<String>,
) {
    match extract(&entry.body)
        .map(|s| truncate_summary(&strip_wikilinks(&s)))
        .filter(|s| !s.is_empty())
    {
        Some(summary) => writeln!(out, "- [[{}]] — {summary}", entry.link_target).unwrap(),
        None => writeln!(out, "- [[{}]]", entry.link_target).unwrap(),
    }
}

/// Render a summary as plain prose: `[[target|display]]` → `display`, `[[target]]` →
/// `target`. A catalog summary is a one-liner *about* a page, not a place for links — the
/// entry's own `[[link]]` is the only navigable target on the line.
fn strip_wikilinks(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(start) = rest.find("[[") {
        out.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        match after.find("]]") {
            Some(end) => {
                let inner = &after[..end];
                out.push_str(inner.rsplit_once('|').map_or(inner, |(_, display)| display));
                rest = &after[end + 2..];
            }
            None => {
                // Unterminated `[[` — emit verbatim and stop.
                out.push_str("[[");
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

/// Trim an extracted summary to its first sentence so a catalog entry stays a scannable
/// one-liner instead of inlining a whole paragraph — the rustdoc/Sphinx first-sentence
/// convention. Sentence end = `.`/`?`/`!`/`。` followed by whitespace or EOS (covers Korean
/// `…다.`/`…음.` terminals). If no boundary falls within `MAX_SUMMARY_BYTES`, cut at the last
/// word boundary under the budget and append an ellipsis, so an unbounded first line can't
/// bloat the index (the bloat the single-file catalog is designed to avoid).
fn truncate_summary(s: &str) -> String {
    let s = s.trim();
    let first = first_sentence(s);
    if first.len() <= MAX_SUMMARY_BYTES {
        return first.to_string();
    }
    let mut cut = MAX_SUMMARY_BYTES;
    while cut > 0 && !s.is_char_boundary(cut) {
        cut -= 1;
    }
    let head = &s[..cut];
    let head = head.rsplit_once(' ').map_or(head, |(a, _)| a).trim_end();
    format!("{head}…")
}

const MAX_SUMMARY_BYTES: usize = 200;

/// The first sentence of `s` (through the terminal punctuation), or all of `s` if no
/// sentence boundary is present.
fn first_sentence(s: &str) -> &str {
    for (idx, ch) in s.char_indices() {
        if matches!(ch, '.' | '?' | '!' | '。') {
            let rest = &s[idx + ch.len_utf8()..];
            if rest.is_empty() || rest.starts_with(char::is_whitespace) {
                return &s[..idx + ch.len_utf8()];
            }
        }
    }
    s
}

/// Return the first non-blank, non-`#`-heading line that sits between `## {heading}`
/// and the next `## ` line. Used for concept (`## 핵심`) and document (`## 요약`)
/// summaries.
///
/// Heading match is exact (no leading/trailing whitespace before `##`). Returns `None`
/// if the heading isn't present or has no non-blank content before the next section.
pub fn first_line_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        // Next section header ends the search.
        if trimmed.starts_with("## ") {
            return None;
        }
        let content = trimmed.trim();
        if content.is_empty() {
            continue;
        }
        // Skip sub-headings (`### `, `#### `, …) and continue looking for the first
        // body line of the section.
        if content.starts_with('#') {
            continue;
        }
        return Some(content.to_string());
    }
    None
}

/// Like [`first_line_under_heading`] but specifically extracts the first list bullet
/// (`- `) underneath the section. Used by daily pages, which always lead `## 요약`
/// with a bulleted summary.
fn first_bullet_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        if trimmed.starts_with("## ") {
            return None;
        }
        let content = trimmed.trim_start();
        if let Some(rest) = content.strip_prefix("- ") {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

/// Return the text of the first `### ` sub-heading that appears under `## {heading}`.
/// Used for work-log pages where the topic name is encoded as `### Topic`.
fn first_subheading_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        if trimmed.starts_with("## ") {
            return None;
        }
        if let Some(rest) = trimmed.trim_start().strip_prefix("### ") {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_file(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    #[test]
    fn empty_vault_yields_header_only() {
        let tmp = TempDir::new().unwrap();
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.starts_with("# Wiki Index"));
        assert!(out.contains("0 pages"));
        // No category sections should be rendered.
        assert!(!out.contains("## 개념"));
        assert!(!out.contains("## 문서"));
    }

    #[test]
    fn concept_section_uses_korean_heading_extractor() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/agentic-ai.md",
            "---\nid: agentic-ai\ntitle: \"Agentic AI\"\n---\n\n# Agentic AI\n\n\
             ## 핵심\n\n자율적으로 도구를 사용하는 AI 에이전트 패러다임.\n\n## 관련\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 개념 (1)"));
        assert!(out.contains("[[agentic-ai|Agentic AI]]"));
        assert!(out.contains("자율적으로 도구를 사용하는 AI 에이전트 패러다임."));
    }

    #[test]
    fn index_extracts_summary_across_locale_switch() {
        // A page authored under KO (`## 핵심`) must still get its one-liner after a ko→en
        // `vault.locale` switch (build with En) — READ tolerates any locale's heading; only
        // WRITE uses the current one. Without Locale::ALL the summary would silently vanish.
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/rag.md",
            "---\nid: rag\ntitle: \"RAG\"\ncategory: ai-ml\n---\n\n## 핵심\n\n검색 증강 생성.\n",
        );
        let out = build_index(tmp.path(), Locale::En, &VaultDirs::default()).unwrap();
        assert!(
            out.contains("[[rag|RAG]] — 검색 증강 생성."),
            "a KO-heading page must still yield its index summary after a locale switch:\n{out}"
        );
    }

    #[test]
    fn english_locale_uses_summary_heading_for_documents() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/documents/whitepaper.md",
            "---\nid: whitepaper\ntitle: White Paper\n---\n\n# White Paper\n\n\
             ## Summary\n\nA short overview of the paper.\n\n## Content\n",
        );
        let out = build_index(tmp.path(), Locale::En, &VaultDirs::default()).unwrap();
        assert!(out.contains("## Documents (1)"));
        assert!(out.contains("[[wiki/documents/whitepaper]]"));
        assert!(out.contains("A short overview of the paper."));
    }

    #[test]
    fn daily_section_is_grouped_by_source_id() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "daily/email-digest/2026-05-22.md",
            "---\nid: e-1\ntitle: Email\n---\n\n## 요약\n\n- 첫 번째 메일 요약\n- 두 번째\n",
        );
        write_file(
            tmp.path(),
            "daily/team-slack/2026-05-22.md",
            "---\nid: s-1\ntitle: Slack\n---\n\n## 요약\n\n- 슬랙 트렌드\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 일일 — email-digest (1)"));
        assert!(out.contains("## 일일 — team-slack (1)"));
        assert!(out.contains("[[daily/email-digest/2026-05-22]] — 첫 번째 메일 요약"));
        assert!(out.contains("[[daily/team-slack/2026-05-22]] — 슬랙 트렌드"));
    }

    #[test]
    fn work_log_uses_first_subheading() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "me/work-log/2026-05-22.md",
            "---\nid: w-1\ntitle: Work\n---\n\n## 주제별 요약\n\n### 태블로 MCP\n- 미팅\n\n### 다른 주제\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 업무 로그 (1)"));
        assert!(out.contains("[[me/work-log/2026-05-22]] — 태블로 MCP"));
    }

    #[test]
    fn exploration_section_uses_question_heading() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/explorations/api-replay.md",
            "---\nid: api-replay\ntitle: \"API Replay\"\n---\n\n# API Replay\n\n\
             ## 질문\n\nAPI 호출만으로 자동화 가능한가?\n\n## 종합\n\n가능하다.\n\n## 근거\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 탐구 (1)"));
        assert!(out.contains("[[wiki/explorations/api-replay]]"));
        assert!(out.contains("API 호출만으로 자동화 가능한가?"));
    }

    #[test]
    fn synthesis_section_uses_narrative_not_period_or_table() {
        // Real review/themes structure: a monthly review leads with `## 기간` (date) and a
        // `## 카테고리 분포` table BEFORE its `## 핵심 요약`. The index must extract the
        // narrative section, not the body's first non-heading line (which would be the date).
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "synthesis/weekly/2026-W21.md",
            "---\nid: w-syn\ntitle: Weekly\n---\n\n# Weekly\n\n## 이번 주 핵심 주제\n\n\
             ### 1. Focus\n\nThis week we focused on X.\n",
        );
        write_file(
            tmp.path(),
            "me/monthly/2026-05.md",
            "---\nid: m\ntitle: May\n---\n\n# May\n\n## 기간\n\n2026-05-01 ~ 2026-05-31\n\n\
             ## 핵심 요약\n\nMay summary.\n\n## 카테고리 분포\n\n| a | 1 | 100% |\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 종합 (2)"));
        // The narrative `## 핵심 요약`, NOT the `## 기간` date that precedes it.
        assert!(
            out.contains("[[me/monthly/2026-05]] — May summary."),
            "monthly index summary must be the narrative, not the period date:\n{out}"
        );
        assert!(
            !out.contains("2026-05-01 ~"),
            "period date must not be the summary:\n{out}"
        );
        assert!(out.contains("[[synthesis/weekly/2026-W21]] — This week we focused on X."));
    }

    #[test]
    fn files_without_frontmatter_are_skipped() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/no-front.md",
            "# Title\n\n## 핵심\n\nSome content.\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/with-front.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nKept.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        // Only the frontmatter-bearing page should show up.
        assert!(out.contains("## 개념 (1)"));
        assert!(out.contains("[[with-front|X]] — Kept."));
        assert!(!out.contains("no-front"));
    }

    #[test]
    fn agents_md_and_existing_index_are_not_listed() {
        let tmp = TempDir::new().unwrap();
        // Pre-existing index and schema doc; should never appear in the new index.
        write_file(
            tmp.path(),
            "wiki/index.md",
            "---\nid: idx\n---\n\n# Old\n\n## 핵심\n\nOld body.\n",
        );
        write_file(
            tmp.path(),
            "wiki/AGENTS.md",
            "---\nid: a\n---\n\n# Agents\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nReal.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(!out.contains("Old body"));
        assert!(!out.contains("[[Agents]]"));
        assert!(out.contains("[[x|X]]"));
    }

    #[test]
    fn concepts_render_inline_grouped_by_category_never_split() {
        // The catalog is a SINGLE page: concepts render under `### {category}` sub-headings
        // inside index.md, never as separate `wiki/index/` sub-page files. (log.md/map.md are
        // likewise single — see the design rationale on `build_index`.)
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/rag.md",
            "---\nid: rag\ntitle: \"RAG\"\ncategory: ai-ml\n---\n\n## 핵심\n\n검색 증강 생성.\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/k8s.md",
            "---\nid: k8s\ntitle: \"Kubernetes\"\ncategory: infra\n---\n\n## 핵심\n\n컨테이너 오케스트레이션.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 개념 (2)"));
        assert!(out.contains("### ai-ml (1)"));
        assert!(out.contains("### infra (1)"));
        assert!(out.contains("[[rag|RAG]] — 검색 증강 생성."));
        // No split sub-page directory is ever created.
        assert!(!tmp.path().join("wiki/index").exists());
    }

    #[test]
    fn summary_wikilinks_are_rendered_as_plain_text() {
        // A `[[…]]` in a page's summary prose must become plain text in the catalog, so the
        // only link on the entry line is the entry's own — otherwise `graph index-sync`
        // would read the summary link as a second catalog entry.
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\ncategory: ai-ml\n---\n\n## 핵심\n\n[[벡터-db|벡터 DB]] 위에 구축한 [[rag]] 시스템.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(
            out.contains("- [[x|X]] — 벡터 DB 위에 구축한 rag 시스템."),
            "summary wikilinks must be flattened to plain text:\n{out}"
        );
    }

    #[test]
    fn summary_is_truncated_to_first_sentence() {
        // A multi-sentence `## 핵심` is bounded to its first sentence so each catalog line
        // stays a scannable one-liner (rustdoc's first-sentence convention); the rest lives
        // on the concept page, reachable by hover/search.
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\ncategory: ai-ml\n---\n\n## 핵심\n\n첫 문장이다. 둘째 문장은 인덱스에 안 들어간다. 셋째도.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("첫 문장이다."), "first sentence kept:\n{out}");
        assert!(
            !out.contains("둘째 문장"),
            "later sentences dropped:\n{out}"
        );
    }

    #[test]
    fn nested_pages_keep_their_subdirectory_in_path_and_link() {
        // A page nested under a group dir must keep its subdirectory — otherwise two
        // same-stem pages in different subdirs collide and links point at the wrong file.
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/documents/team-a/spec.md",
            "---\nid: a\n---\n\n## 핵심\n\nA spec.\n",
        );
        write_file(
            tmp.path(),
            "wiki/documents/team-b/spec.md",
            "---\nid: b\n---\n\n## 핵심\n\nB spec.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("[[wiki/documents/team-a/spec]]"), "got: {out}");
        assert!(out.contains("[[wiki/documents/team-b/spec]]"), "got: {out}");
    }

    #[test]
    fn first_line_under_heading_basic() {
        let body = "# Title\n\n## 요약\n\nFirst real line.\nSecond line.\n\n## 다음\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("First real line.".to_string())
        );
    }

    #[test]
    fn first_line_under_heading_returns_none_when_missing() {
        let body = "# Title\n\n## 다른\n\nbody\n";
        assert!(first_line_under_heading(body, "요약").is_none());
    }

    #[test]
    fn first_line_under_heading_stops_at_next_section() {
        let body = "## 요약\n\n## 다음\n\nThis is in next section.\n";
        assert!(first_line_under_heading(body, "요약").is_none());
    }

    #[test]
    fn first_line_under_heading_skips_blank_lines() {
        let body = "## 요약\n\n\n\nFinally some text.\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("Finally some text.".to_string())
        );
    }

    #[test]
    fn first_line_under_heading_skips_subheadings() {
        let body = "## 요약\n\n### subhead\n\nActual content.\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("Actual content.".to_string())
        );
    }

    #[test]
    fn first_bullet_under_heading_picks_first_bullet() {
        let body = "## 요약\n\n- One\n- Two\n\n## Next\n";
        assert_eq!(
            first_bullet_under_heading(body, "요약"),
            Some("One".to_string())
        );
    }

    #[tokio::test]
    async fn write_index_atomic_no_temp_leftover() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nbody\n",
        );
        let path = write_index(tmp.path(), Locale::Ko, &VaultDirs::default())
            .await
            .unwrap();
        assert!(path.ends_with("wiki/index.md"));
        let content = tokio::fs::read_to_string(&path).await.unwrap();
        assert!(content.contains("[[x|X]]"));

        // Ensure no `.index.md.*` temp leftovers in wiki/.
        let mut entries = tokio::fs::read_dir(tmp.path().join("wiki")).await.unwrap();
        while let Some(entry) = entries.next_entry().await.unwrap() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            assert!(!name.ends_with(".tmp"), "leftover temp file: {name}");
        }
    }

    #[test]
    fn custom_dirs_produce_correct_paths() {
        let tmp = TempDir::new().unwrap();
        let dirs = VaultDirs {
            wiki: "knowledge".into(),
            daily: "feed".into(),
            personal: "my-notes".into(),
            synthesis: "team-synth".into(),
            ..Default::default()
        };
        write_file(
            tmp.path(),
            "knowledge/concepts/llm-wiki.md",
            "---\nid: llm-wiki\ntitle: \"LLM Wiki\"\ncategory: ai\n---\n\n## Synthesis\n\nA wiki.\n",
        );
        write_file(
            tmp.path(),
            "feed/ai-news/2026-05-20.md",
            "---\nid: d1\ntitle: \"News\"\n---\n\n## Summary\n\nHeadlines.\n",
        );
        write_file(
            tmp.path(),
            "team-synth/weekly/2026-W21.md",
            "---\nid: ts\ntitle: \"W21\"\n---\n\n## Key Themes\n\nThemes.\n",
        );
        let out = build_index(tmp.path(), Locale::En, &dirs).unwrap();
        assert!(out.contains("[[llm-wiki|LLM Wiki]]"));
        assert!(out.contains("[[feed/ai-news/2026-05-20]]"));
        assert!(out.contains("[[team-synth/weekly/2026-W21]]"));
        assert!(!out.contains("wiki/"));
        assert!(!out.contains("daily/"));
    }
}
