//! `wiki/index.md` builder — a deterministic, hierarchical catalog of every vault page.
//!
//! Walks the vault directories (`wiki/concepts/`, `wiki/documents/`, `daily/{source}/`,
//! `me/work-log/`, plus the four synthesis tiers), parses each markdown file's
//! frontmatter via [`lk_core::frontmatter::parse_page`], extracts a one-line summary
//! from the page body, groups entries by category, and renders a single markdown
//! document. No LLM, no heuristics — running it twice produces the same bytes.
//!
//! Section labels and heading targets come from [`lk_core::i18n`] so the index honors
//! `vault.locale` like the rest of the pipeline.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use jiff::Timestamp;
use lk_core::frontmatter::parse_page;
use lk_core::i18n::Locale;
use walkdir::WalkDir;

use crate::VaultError;

/// Monotonic sequence counter for atomic temp file uniqueness (mirrors `TMP_SEQ` in
/// `writer.rs` but scoped to index writes).
static INDEX_TMP_SEQ: AtomicU64 = AtomicU64::new(0);

/// Build the `wiki/index.md` body for the vault at `vault_root`, using `locale` to pick
/// section headings and the body-heading targets used by the one-line extractors.
///
/// Returns the rendered markdown (caller writes it). Walks the vault filesystem
/// directly — directories that don't exist are simply skipped (an empty vault yields
/// just the header).
pub fn build_index(vault_root: &Path, locale: Locale) -> Result<String, VaultError> {
    let strings = locale.strings();

    let concepts = collect_dir(vault_root, Path::new("wiki/concepts"));
    let documents = collect_dir(vault_root, Path::new("wiki/documents"));

    // daily/ holds one sub-directory per source ID. We keep them as separate groups so
    // the index shows pages-per-source counts and stable ordering.
    let mut daily_groups: BTreeMap<String, Vec<Entry>> = BTreeMap::new();
    let daily_root = vault_root.join("daily");
    if daily_root.is_dir() {
        let mut sub_dirs: Vec<(String, PathBuf)> = Vec::new();
        for entry in std::fs::read_dir(&daily_root)? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                let name = entry.file_name().to_string_lossy().into_owned();
                sub_dirs.push((name, entry.path()));
            }
        }
        sub_dirs.sort_by(|a, b| a.0.cmp(&b.0));
        for (source_id, dir) in sub_dirs {
            let rel = Path::new("daily").join(&source_id);
            let entries = collect_files(&rel, &dir);
            if !entries.is_empty() {
                daily_groups.insert(source_id, entries);
            }
        }
    }

    let worklog = collect_dir(vault_root, Path::new("me/work-log"));

    // Synthesis tiers are merged into one bucket so the index has a single "synthesis"
    // section. Each entry keeps its full vault-relative path so the wikilink target is
    // unambiguous.
    let mut synthesis: Vec<Entry> = Vec::new();
    for sub in &[
        "weekly/synthesis",
        "weekly/me",
        "monthly/me",
        "quarterly/me",
        "annually/me",
    ] {
        synthesis.extend(collect_dir(vault_root, Path::new(sub)));
    }
    synthesis.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));

    let total = concepts.len()
        + documents.len()
        + daily_groups.values().map(Vec::len).sum::<usize>()
        + worklog.len()
        + synthesis.len();

    let timestamp = Timestamp::now().to_string();

    let mut out = String::new();
    writeln!(out, "# Wiki Index").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "> Generated by `lore wiki index` — {total} pages at {timestamp}"
    )
    .unwrap();

    if !concepts.is_empty() {
        let heading = strings.concept_synthesis;
        let mut by_category: BTreeMap<String, Vec<&Entry>> = BTreeMap::new();
        let mut uncategorized: Vec<&Entry> = Vec::new();
        for entry in &concepts {
            match &entry.category {
                Some(cat) => by_category.entry(cat.clone()).or_default().push(entry),
                None => uncategorized.push(entry),
            }
        }

        writeln!(out).unwrap();
        writeln!(out, "## {} ({})", strings.index_concepts, concepts.len()).unwrap();

        for (cat, entries) in &by_category {
            writeln!(out).unwrap();
            writeln!(out, "### {cat} ({})", entries.len()).unwrap();
            writeln!(out).unwrap();
            for entry in entries {
                let summary = first_line_under_heading(&entry.body, heading).unwrap_or_default();
                if summary.is_empty() {
                    writeln!(out, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(out, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
        }

        if !uncategorized.is_empty() {
            writeln!(out).unwrap();
            writeln!(out, "### 미분류 ({})", uncategorized.len()).unwrap();
            writeln!(out).unwrap();
            for entry in &uncategorized {
                let summary = first_line_under_heading(&entry.body, heading).unwrap_or_default();
                if summary.is_empty() {
                    writeln!(out, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(out, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
        }
    }

    if !documents.is_empty() {
        let heading = strings.summary;
        render_group(
            &mut out,
            strings.index_documents,
            documents.len(),
            &documents,
            |body| first_line_under_heading(body, heading),
        );
    }

    for (source_id, entries) in &daily_groups {
        let summary_heading = strings.summary;
        let title = format!("{} — {}", strings.index_daily, source_id);
        render_group(&mut out, &title, entries.len(), entries, |body| {
            first_bullet_under_heading(body, summary_heading)
                .or_else(|| first_line_under_heading(body, summary_heading))
        });
    }

    if !worklog.is_empty() {
        let heading = strings.topic_summary;
        render_group(
            &mut out,
            strings.index_worklog,
            worklog.len(),
            &worklog,
            |body| first_subheading_under_heading(body, heading),
        );
    }

    if !synthesis.is_empty() {
        render_group(
            &mut out,
            strings.index_synthesis,
            synthesis.len(),
            &synthesis,
            first_non_blank_body_line,
        );
    }

    Ok(out)
}

/// Build the index and write it atomically to `<vault_root>/wiki/index.md`.
///
/// The temp file lives next to the final path so the rename is on the same filesystem
/// and therefore atomic. Returns the absolute path that was written.
pub async fn write_index(vault_root: &Path, locale: Locale) -> Result<PathBuf, VaultError> {
    let content = build_index(vault_root, locale)?;
    let wiki_dir = vault_root.join("wiki");
    tokio::fs::create_dir_all(&wiki_dir).await?;
    let final_path = wiki_dir.join("index.md");
    let seq = INDEX_TMP_SEQ.fetch_add(1, Ordering::Relaxed);
    let tmp_path = wiki_dir.join(format!(".index.md.{}.{seq}.tmp", std::process::id()));

    match tokio::fs::write(&tmp_path, &content).await {
        Ok(()) => {}
        Err(e) => {
            let _ = tokio::fs::remove_file(&tmp_path).await;
            return Err(e.into());
        }
    }
    if let Err(e) = tokio::fs::rename(&tmp_path, &final_path).await {
        let _ = tokio::fs::remove_file(&tmp_path).await;
        return Err(e.into());
    }
    Ok(final_path)
}

/// A single catalog entry: vault-relative path, the slug used in the wikilink, and the
/// raw page body (used to extract a per-category one-liner at render time).
struct Entry {
    rel_path: String,
    /// Slug for the wikilink target. Daily/work-log/synthesis pages use the full
    /// vault-relative path (without `.md`) so the link is unambiguous; concepts use
    /// the page title or filename stem.
    link_target: String,
    body: String,
    category: Option<String>,
}

fn collect_dir(vault_root: &Path, rel: &Path) -> Vec<Entry> {
    let abs = vault_root.join(rel);
    if !abs.is_dir() {
        return Vec::new();
    }
    collect_files(rel, &abs)
}

fn collect_files(rel_dir: &Path, abs_dir: &Path) -> Vec<Entry> {
    let mut entries: Vec<Entry> = Vec::new();
    for w in WalkDir::new(abs_dir).follow_links(false) {
        let w = match w {
            Ok(w) => w,
            Err(e) => {
                tracing::warn!(error = %e, dir = %abs_dir.display(), "skipping unreadable path");
                continue;
            }
        };
        if !w.file_type().is_file() {
            continue;
        }
        let path = w.path();
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        // Skip Lorekeeper's reserved meta files (the index catalog itself and the
        // AGENTS.md schema doc) — they are not knowledge pages.
        if let Some(name) = path.file_name().and_then(|n| n.to_str())
            && lk_core::vault_path::RESERVED_WIKI_FILES.contains(&name)
        {
            continue;
        }

        let raw = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!(error = %e, path = %path.display(), "skipping unreadable file");
                continue;
            }
        };
        let page = match parse_page(&raw) {
            Ok(p) => p,
            Err(e) => {
                tracing::warn!(error = %e, path = %path.display(), "skipping malformed frontmatter");
                continue;
            }
        };
        // Files without any frontmatter are skipped — only Lorekeeper-managed pages
        // belong in the index.
        if page.frontmatter.fields.is_empty() {
            continue;
        }

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        let rel_path = rel_dir.join(format!("{stem}.md"));
        let rel_path = rel_path.to_string_lossy().replace('\\', "/");
        let rel_dir_str = rel_dir.to_string_lossy().replace('\\', "/");

        // Concepts wikilink by title/stem; everything else wikilinks by vault path so
        // identically-named daily pages across sources stay distinct.
        let link_target = if rel_dir_str == "wiki/concepts" {
            page.frontmatter
                .get("title")
                .and_then(|v| v.as_str())
                .map(str::to_string)
                .filter(|s| !s.is_empty())
                .unwrap_or_else(|| stem.clone())
        } else {
            let no_ext = format!("{rel_dir_str}/{stem}");
            no_ext
        };

        let category = page
            .frontmatter
            .get("category")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .map(String::from);

        entries.push(Entry {
            rel_path,
            link_target,
            body: page.body,
            category,
        });
    }
    entries.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));
    entries
}

fn render_group(
    out: &mut String,
    title: &str,
    count: usize,
    entries: &[Entry],
    extract: impl Fn(&str) -> Option<String>,
) {
    writeln!(out).unwrap();
    writeln!(out, "## {title} ({count})").unwrap();
    writeln!(out).unwrap();
    for entry in entries {
        let summary = extract(&entry.body).unwrap_or_default();
        if summary.is_empty() {
            writeln!(out, "- [[{}]]", entry.link_target).unwrap();
        } else {
            writeln!(out, "- [[{}]] — {summary}", entry.link_target).unwrap();
        }
    }
}

/// Return the first non-blank, non-`#`-heading line that sits between `## {heading}`
/// and the next `## ` line. Used for concept (`## 핵심`) and document (`## 요약`)
/// summaries.
///
/// Heading match is exact (no leading/trailing whitespace before `##`). Returns `None`
/// if the heading isn't present or has no non-blank content before the next section.
pub fn first_line_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        // Next section header ends the search.
        if trimmed.starts_with("## ") {
            return None;
        }
        let content = trimmed.trim();
        if content.is_empty() {
            continue;
        }
        // Skip sub-headings (`### `, `#### `, …) and continue looking for the first
        // body line of the section.
        if content.starts_with('#') {
            continue;
        }
        return Some(content.to_string());
    }
    None
}

/// Like [`first_line_under_heading`] but specifically extracts the first list bullet
/// (`- `) underneath the section. Used by daily pages, which always lead `## 요약`
/// with a bulleted summary.
fn first_bullet_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        if trimmed.starts_with("## ") {
            return None;
        }
        let content = trimmed.trim_start();
        if let Some(rest) = content.strip_prefix("- ") {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

/// Return the text of the first `### ` sub-heading that appears under `## {heading}`.
/// Used for work-log pages where the topic name is encoded as `### Topic`.
fn first_subheading_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        if trimmed.starts_with("## ") {
            return None;
        }
        if let Some(rest) = trimmed.trim_start().strip_prefix("### ") {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

/// Fallback extractor for synthesis pages: the first non-blank, non-heading body line.
fn first_non_blank_body_line(body: &str) -> Option<String> {
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with('#') {
            continue;
        }
        // Strip a leading list marker so the one-liner reads naturally.
        let trimmed = trimmed
            .strip_prefix("- ")
            .or_else(|| trimmed.strip_prefix("* "))
            .unwrap_or(trimmed);
        return Some(trimmed.to_string());
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_file(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    #[test]
    fn empty_vault_yields_header_only() {
        let tmp = TempDir::new().unwrap();
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        assert!(out.starts_with("# Wiki Index"));
        assert!(out.contains("0 pages"));
        // No category sections should be rendered.
        assert!(!out.contains("## 개념"));
        assert!(!out.contains("## 문서"));
    }

    #[test]
    fn concept_section_uses_korean_heading_extractor() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/agentic-ai.md",
            "---\nid: agentic-ai\ntitle: \"Agentic AI\"\n---\n\n# Agentic AI\n\n\
             ## 핵심\n\n자율적으로 도구를 사용하는 AI 에이전트 패러다임.\n\n## 관련\n",
        );
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        assert!(out.contains("## 개념 (1)"));
        assert!(out.contains("[[Agentic AI]]"));
        assert!(out.contains("자율적으로 도구를 사용하는 AI 에이전트 패러다임."));
    }

    #[test]
    fn english_locale_uses_summary_heading_for_documents() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/documents/whitepaper.md",
            "---\nid: whitepaper\ntitle: White Paper\n---\n\n# White Paper\n\n\
             ## Summary\n\nA short overview of the paper.\n\n## Content\n",
        );
        let out = build_index(tmp.path(), Locale::En).unwrap();
        assert!(out.contains("## Documents (1)"));
        assert!(out.contains("[[wiki/documents/whitepaper]]"));
        assert!(out.contains("A short overview of the paper."));
    }

    #[test]
    fn daily_section_is_grouped_by_source_id() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "daily/email-digest/2026-05-22.md",
            "---\nid: e-1\ntitle: Email\n---\n\n## 요약\n\n- 첫 번째 메일 요약\n- 두 번째\n",
        );
        write_file(
            tmp.path(),
            "daily/team-slack/2026-05-22.md",
            "---\nid: s-1\ntitle: Slack\n---\n\n## 요약\n\n- 슬랙 트렌드\n",
        );
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        assert!(out.contains("## 일일 — email-digest (1)"));
        assert!(out.contains("## 일일 — team-slack (1)"));
        assert!(out.contains("[[daily/email-digest/2026-05-22]] — 첫 번째 메일 요약"));
        assert!(out.contains("[[daily/team-slack/2026-05-22]] — 슬랙 트렌드"));
    }

    #[test]
    fn worklog_uses_first_subheading() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "me/work-log/2026-05-22.md",
            "---\nid: w-1\ntitle: Work\n---\n\n## 주제별 요약\n\n### 태블로 MCP\n- 미팅\n\n### 다른 주제\n",
        );
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        assert!(out.contains("## 업무 로그 (1)"));
        assert!(out.contains("[[me/work-log/2026-05-22]] — 태블로 MCP"));
    }

    #[test]
    fn synthesis_section_merges_all_tiers() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "weekly/synthesis/2026-W21.md",
            "---\nid: w-syn\ntitle: Weekly\n---\n\n# Weekly\n\nThis week we focused on X.\n",
        );
        write_file(
            tmp.path(),
            "monthly/me/2026-05.md",
            "---\nid: m\ntitle: May\n---\n\n# May\n\nMay summary.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        assert!(out.contains("## 종합 (2)"));
        assert!(out.contains("[[monthly/me/2026-05]] — May summary."));
        assert!(out.contains("[[weekly/synthesis/2026-W21]] — This week we focused on X."));
    }

    #[test]
    fn files_without_frontmatter_are_skipped() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/no-front.md",
            "# Title\n\n## 핵심\n\nSome content.\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/with-front.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nKept.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        // Only the frontmatter-bearing page should show up.
        assert!(out.contains("## 개념 (1)"));
        assert!(out.contains("[[X]] — Kept."));
        assert!(!out.contains("no-front"));
    }

    #[test]
    fn agents_md_and_existing_index_are_not_listed() {
        let tmp = TempDir::new().unwrap();
        // Pre-existing index and schema doc; should never appear in the new index.
        write_file(
            tmp.path(),
            "wiki/index.md",
            "---\nid: idx\n---\n\n# Old\n\n## 핵심\n\nOld body.\n",
        );
        write_file(
            tmp.path(),
            "wiki/AGENTS.md",
            "---\nid: a\n---\n\n# Agents\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nReal.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko).unwrap();
        assert!(!out.contains("Old body"));
        assert!(!out.contains("[[Agents]]"));
        assert!(out.contains("[[X]]"));
    }

    #[test]
    fn first_line_under_heading_basic() {
        let body = "# Title\n\n## 요약\n\nFirst real line.\nSecond line.\n\n## 다음\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("First real line.".to_string())
        );
    }

    #[test]
    fn first_line_under_heading_returns_none_when_missing() {
        let body = "# Title\n\n## 다른\n\nbody\n";
        assert!(first_line_under_heading(body, "요약").is_none());
    }

    #[test]
    fn first_line_under_heading_stops_at_next_section() {
        let body = "## 요약\n\n## 다음\n\nThis is in next section.\n";
        assert!(first_line_under_heading(body, "요약").is_none());
    }

    #[test]
    fn first_line_under_heading_skips_blank_lines() {
        let body = "## 요약\n\n\n\nFinally some text.\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("Finally some text.".to_string())
        );
    }

    #[test]
    fn first_line_under_heading_skips_subheadings() {
        let body = "## 요약\n\n### subhead\n\nActual content.\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("Actual content.".to_string())
        );
    }

    #[test]
    fn first_bullet_under_heading_picks_first_bullet() {
        let body = "## 요약\n\n- One\n- Two\n\n## Next\n";
        assert_eq!(
            first_bullet_under_heading(body, "요약"),
            Some("One".to_string())
        );
    }

    #[tokio::test]
    async fn write_index_atomic_no_temp_leftover() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nbody\n",
        );
        let path = write_index(tmp.path(), Locale::Ko).await.unwrap();
        assert!(path.ends_with("wiki/index.md"));
        let content = tokio::fs::read_to_string(&path).await.unwrap();
        assert!(content.contains("[[X]]"));

        // Ensure no `.index.md.*` temp leftovers in wiki/.
        let mut entries = tokio::fs::read_dir(tmp.path().join("wiki")).await.unwrap();
        while let Some(entry) = entries.next_entry().await.unwrap() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            assert!(!name.ends_with(".tmp"), "leftover temp file: {name}");
        }
    }
}
