//! Wiki index builder — a deterministic, hierarchical catalog of every vault page.
//!
//! Walks the vault directories (wiki concepts/documents/explorations, daily sources,
//! personal work-log, and synthesis tiers), parses each markdown file's
//! frontmatter via [`lk_core::frontmatter::parse_page`], extracts a one-line summary
//! from the page body, groups entries by category, and renders a single markdown
//! document. No LLM, no heuristics — running it twice produces the same bytes.
//!
//! Section labels and heading targets come from [`lk_core::i18n`] so the index honors
//! `vault.locale` like the rest of the pipeline.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use lk_core::config::VaultDirs;
use lk_core::frontmatter::parse_page;
use lk_core::i18n::Locale;
use walkdir::WalkDir;

use crate::{VaultError, VaultWriter};

/// Output from `build_index`: the main index page plus optional per-category sub-pages
/// when the concept count exceeds the split threshold.
pub struct IndexResult {
    pub main: String,
    pub sub_pages: Vec<(String, String)>,
}

/// Build the wiki index body for the vault at `vault_root`, using `locale` to pick
/// section headings and the body-heading targets used by the one-line extractors.
///
/// Returns the rendered markdown (caller writes it). Walks the vault filesystem
/// directly — directories that don't exist are simply skipped (an empty vault yields
/// just the header).
pub fn build_index(
    vault_root: &Path,
    locale: Locale,
    index_split_threshold: usize,
    dirs: &VaultDirs,
) -> Result<IndexResult, VaultError> {
    let strings = locale.strings();

    let wiki = Path::new(&dirs.wiki);
    let concept_rel = wiki.join("concepts");
    let concept_rel_str = concept_rel.to_string_lossy().replace('\\', "/");
    let concepts =
        collect_dir_grouped(vault_root, &concept_rel, "category", Some(&concept_rel_str));
    // Group documents by `document_type` — a field EVERY document carries — so the
    // catalog buckets consistently (vs `source_project`, which only some documents have).
    let documents = collect_dir_grouped(vault_root, &wiki.join("documents"), "document_type", None);
    let explorations = collect_dir(vault_root, &wiki.join("explorations"));

    // daily/ holds one sub-directory per source ID. We keep them as separate groups so
    // the index shows pages-per-source counts and stable ordering.
    let mut daily_groups: BTreeMap<String, Vec<Entry>> = BTreeMap::new();
    let daily_root = vault_root.join(&dirs.daily);
    if daily_root.is_dir() {
        let mut sub_dirs: Vec<(String, PathBuf)> = Vec::new();
        for entry in std::fs::read_dir(&daily_root)? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                let name = entry.file_name().to_string_lossy().into_owned();
                sub_dirs.push((name, entry.path()));
            }
        }
        sub_dirs.sort_by(|a, b| a.0.cmp(&b.0));
        for (source_id, dir) in sub_dirs {
            let rel = Path::new(&dirs.daily).join(&source_id);
            let entries = collect_files(&rel, &dir, "category", None);
            if !entries.is_empty() {
                daily_groups.insert(source_id, entries);
            }
        }
    }

    let worklog = collect_dir(vault_root, &Path::new(&dirs.personal).join("work-log"));

    // Synthesis tiers are merged into one bucket so the index has a single "synthesis"
    // section. Each entry keeps its full vault-relative path so the wikilink target is
    // unambiguous.
    let mut synthesis: Vec<Entry> = Vec::new();
    let synthesis_dirs = [
        PathBuf::from(&dirs.synthesis).join(&dirs.weekly),
        PathBuf::from(&dirs.personal).join(&dirs.weekly),
        PathBuf::from(&dirs.personal).join(&dirs.monthly),
        PathBuf::from(&dirs.personal).join(&dirs.quarterly),
        PathBuf::from(&dirs.personal).join(&dirs.annual),
    ];
    for sub in &synthesis_dirs {
        synthesis.extend(collect_dir(vault_root, sub));
    }
    synthesis.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));

    let total = concepts.len()
        + documents.len()
        + explorations.len()
        + daily_groups.values().map(Vec::len).sum::<usize>()
        + worklog.len()
        + synthesis.len();

    let mut out = String::new();
    writeln!(out, "# Wiki Index").unwrap();
    writeln!(out).unwrap();
    // No timestamp: the index is a deterministic function of vault content, so an
    // unchanged vault re-renders byte-identical bytes and a re-run is a true no-op
    // (the daily scheduled rebuild relies on this).
    writeln!(out, "> Generated by `lore wiki index` — {total} pages").unwrap();

    let mut sub_pages: Vec<(String, String)> = Vec::new();

    let should_split = |count: usize| index_split_threshold > 0 && count >= index_split_threshold;

    if !concepts.is_empty() {
        let heading = strings.concept_synthesis;
        render_grouped_section(
            &mut out,
            &mut sub_pages,
            &concepts,
            |body| first_line_under_heading(body, heading),
            &GroupedSectionOptions {
                section_title: strings.index_concepts,
                sub_page_prefix: "",
                uncategorized_label: strings.uncategorized,
                split: should_split(concepts.len()),
            },
            dirs,
        );
    }

    if !documents.is_empty() {
        let heading = strings.summary;
        render_grouped_section(
            &mut out,
            &mut sub_pages,
            &documents,
            |body| first_line_under_heading(body, heading),
            &GroupedSectionOptions {
                section_title: strings.index_documents,
                sub_page_prefix: "doc-",
                uncategorized_label: strings.uncategorized,
                split: should_split(documents.len()),
            },
            dirs,
        );
    }

    if !explorations.is_empty() {
        let heading = strings.exploration_question;
        render_group(
            &mut out,
            strings.index_explorations,
            explorations.len(),
            &explorations,
            |body| first_line_under_heading(body, heading),
        );
    }

    let total_daily: usize = daily_groups.values().map(Vec::len).sum();
    let daily_split = should_split(total_daily);

    if daily_split {
        writeln!(out).unwrap();
        writeln!(out, "## {} ({total_daily})", strings.index_daily).unwrap();
        writeln!(out).unwrap();
        for (source_id, entries) in &daily_groups {
            let slug = format!("daily-{source_id}");
            let wiki = &dirs.wiki;
            writeln!(
                out,
                "- [[{wiki}/index/{slug}|{source_id}]] ({})",
                entries.len()
            )
            .unwrap();

            let summary_heading = strings.summary;
            let mut page = String::new();
            writeln!(page, "# {} — {source_id}", strings.index_daily).unwrap();
            writeln!(page).unwrap();
            writeln!(page, "> {}", entries.len()).unwrap();
            writeln!(page).unwrap();
            for entry in entries.iter() {
                let summary = first_bullet_under_heading(&entry.body, summary_heading)
                    .or_else(|| first_line_under_heading(&entry.body, summary_heading))
                    .unwrap_or_default();
                if summary.is_empty() {
                    writeln!(page, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(page, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
            sub_pages.push((format!("{}/index/{slug}.md", dirs.wiki), page));
        }
    } else {
        for (source_id, entries) in &daily_groups {
            let summary_heading = strings.summary;
            let title = format!("{} — {}", strings.index_daily, source_id);
            render_group(&mut out, &title, entries.len(), entries, |body| {
                first_bullet_under_heading(body, summary_heading)
                    .or_else(|| first_line_under_heading(body, summary_heading))
            });
        }
    }

    if !worklog.is_empty() {
        let heading = strings.topic_summary;
        render_group(
            &mut out,
            strings.index_worklog,
            worklog.len(),
            &worklog,
            |body| first_subheading_under_heading(body, heading),
        );
    }

    if !synthesis.is_empty() {
        render_group(
            &mut out,
            strings.index_synthesis,
            synthesis.len(),
            &synthesis,
            first_non_blank_body_line,
        );
    }

    Ok(IndexResult {
        main: out,
        sub_pages,
    })
}

/// Build the index and write it atomically to `<vault_root>/<wiki>/index.md`.
///
/// The temp file lives next to the final path so the rename is on the same filesystem
/// and therefore atomic. Returns the absolute path that was written.
pub async fn write_index(
    vault_root: &Path,
    locale: Locale,
    index_split_threshold: usize,
    dirs: &VaultDirs,
) -> Result<PathBuf, VaultError> {
    let output = build_index(vault_root, locale, index_split_threshold, dirs)?;
    let wiki_dir = vault_root.join(&dirs.wiki);
    let index_dir = wiki_dir.join("index");

    // Every page — sub-pages and the main index alike — goes through the one atomic
    // temp+rename writer, so a crash never leaves a truncated index page. Sub-pages are
    // written before the main index so it never links a not-yet-written sub-page.
    let writer = VaultWriter::new(vault_root);
    for (rel_path, content) in &output.sub_pages {
        writer.write_page(Path::new(rel_path), content).await?;
    }

    let main_rel = Path::new(&dirs.wiki).join("index.md");
    writer.write_page(&main_rel, &output.main).await?;
    let final_path = wiki_dir.join("index.md");

    if index_dir.is_dir() {
        let current: std::collections::HashSet<String> = output
            .sub_pages
            .iter()
            .filter_map(|(p, _)| {
                std::path::Path::new(p)
                    .file_name()?
                    .to_str()
                    .map(String::from)
            })
            .collect();
        let mut entries = tokio::fs::read_dir(&index_dir).await?;
        while let Some(entry) = entries.next_entry().await? {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if name.ends_with(".md") && !current.contains(name.as_ref()) {
                let _ = tokio::fs::remove_file(entry.path()).await;
            }
        }
    }

    Ok(final_path)
}

/// A single catalog entry: vault-relative path, the slug used in the wikilink, and the
/// raw page body (used to extract a per-category one-liner at render time).
struct Entry {
    rel_path: String,
    /// Wikilink target. Daily/work-log/synthesis pages use the full vault-relative
    /// path (without `.md`); concepts use `slug|title` pipe format for correct
    /// resolution by filename while preserving readable display in Obsidian.
    link_target: String,
    body: String,
    category: Option<String>,
}

fn collect_dir(vault_root: &Path, rel: &Path) -> Vec<Entry> {
    collect_dir_grouped(vault_root, rel, "category", None)
}

fn collect_dir_grouped(
    vault_root: &Path,
    rel: &Path,
    group_field: &str,
    concept_rel_dir: Option<&str>,
) -> Vec<Entry> {
    let abs = vault_root.join(rel);
    if !abs.is_dir() {
        return Vec::new();
    }
    collect_files(rel, &abs, group_field, concept_rel_dir)
}

fn collect_files(
    rel_dir: &Path,
    abs_dir: &Path,
    group_field: &str,
    concept_rel_dir: Option<&str>,
) -> Vec<Entry> {
    let mut entries: Vec<Entry> = Vec::new();
    for w in WalkDir::new(abs_dir).follow_links(false) {
        let w = match w {
            Ok(w) => w,
            Err(e) => {
                tracing::warn!(error = %e, dir = %abs_dir.display(), "skipping unreadable path");
                continue;
            }
        };
        if !w.file_type().is_file() {
            continue;
        }
        let path = w.path();
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        // Skip Lorekeeper's reserved meta files (the index catalog itself and the
        // AGENTS.md schema doc) — they are not knowledge pages.
        if let Some(name) = path.file_name().and_then(|n| n.to_str())
            && lk_core::vault_path::RESERVED_WIKI_FILES.contains(&name)
        {
            continue;
        }

        let raw = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!(error = %e, path = %path.display(), "skipping unreadable file");
                continue;
            }
        };
        let page = match parse_page(&raw) {
            Ok(p) => p,
            Err(e) => {
                tracing::warn!(error = %e, path = %path.display(), "skipping malformed frontmatter");
                continue;
            }
        };
        // Files without any frontmatter are skipped — only Lorekeeper-managed pages
        // belong in the index.
        if page.frontmatter.fields.is_empty() {
            continue;
        }

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        // `WalkDir` recurses, so a page may live in a subdirectory of `abs_dir`.
        // Carry that nesting into the vault-relative path (and the wikilink target)
        // instead of flattening every page onto `rel_dir` — otherwise nested pages
        // with the same stem collide and links point at the wrong path.
        let nested = path
            .parent()
            .and_then(|p| p.strip_prefix(abs_dir).ok())
            .filter(|p| !p.as_os_str().is_empty());
        let entry_rel_dir = match nested {
            Some(sub) => rel_dir.join(sub),
            None => rel_dir.to_path_buf(),
        };
        let rel_path = entry_rel_dir.join(format!("{stem}.md"));
        let rel_path = rel_path.to_string_lossy().replace('\\', "/");
        let rel_dir_str = entry_rel_dir.to_string_lossy().replace('\\', "/");

        let link_target = if concept_rel_dir.is_some_and(|c| rel_dir_str == c) {
            let title = page
                .frontmatter
                .get("title")
                .and_then(|v| v.as_str())
                .filter(|s| !s.is_empty() && *s != stem);
            match title {
                Some(t) => format!("{stem}|{t}"),
                None => stem.clone(),
            }
        } else {
            format!("{rel_dir_str}/{stem}")
        };

        let category = page
            .frontmatter
            .get(group_field)
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .map(String::from);

        entries.push(Entry {
            rel_path,
            link_target,
            body: page.body,
            category,
        });
    }
    entries.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));
    entries
}

fn render_group(
    out: &mut String,
    title: &str,
    count: usize,
    entries: &[Entry],
    extract: impl Fn(&str) -> Option<String>,
) {
    writeln!(out).unwrap();
    writeln!(out, "## {title} ({count})").unwrap();
    writeln!(out).unwrap();
    for entry in entries {
        let summary = extract(&entry.body).unwrap_or_default();
        if summary.is_empty() {
            writeln!(out, "- [[{}]]", entry.link_target).unwrap();
        } else {
            writeln!(out, "- [[{}]] — {summary}", entry.link_target).unwrap();
        }
    }
}

struct GroupedSectionOptions<'a> {
    section_title: &'a str,
    sub_page_prefix: &'a str,
    uncategorized_label: &'a str,
    split: bool,
}

fn render_grouped_section(
    out: &mut String,
    sub_pages: &mut Vec<(String, String)>,
    entries: &[Entry],
    extract: impl Fn(&str) -> Option<String>,
    opts: &GroupedSectionOptions<'_>,
    dirs: &VaultDirs,
) {
    let GroupedSectionOptions {
        section_title,
        sub_page_prefix,
        uncategorized_label,
        split,
    } = opts;
    let mut by_group: BTreeMap<String, Vec<&Entry>> = BTreeMap::new();
    let mut ungrouped: Vec<&Entry> = Vec::new();
    for entry in entries {
        match &entry.category {
            Some(g) => by_group.entry(g.clone()).or_default().push(entry),
            None => ungrouped.push(entry),
        }
    }

    writeln!(out).unwrap();
    writeln!(out, "## {section_title} ({})", entries.len()).unwrap();

    if *split {
        writeln!(out).unwrap();
        for (group, group_entries) in &by_group {
            let slug = format!("{sub_page_prefix}{group}");
            let wiki = &dirs.wiki;
            writeln!(
                out,
                "- [[{wiki}/index/{slug}|{group}]] ({})",
                group_entries.len()
            )
            .unwrap();

            let mut page = String::new();
            writeln!(page, "# {group}").unwrap();
            writeln!(page).unwrap();
            writeln!(page, "> {}", group_entries.len()).unwrap();
            writeln!(page).unwrap();
            for entry in group_entries {
                let summary = extract(&entry.body).unwrap_or_default();
                if summary.is_empty() {
                    writeln!(page, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(page, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
            sub_pages.push((format!("{}/index/{slug}.md", dirs.wiki), page));
        }
        if !ungrouped.is_empty() {
            let slug = format!("{sub_page_prefix}uncategorized");
            let wiki = &dirs.wiki;
            writeln!(
                out,
                "- [[{wiki}/index/{slug}|{uncategorized_label}]] ({})",
                ungrouped.len()
            )
            .unwrap();
            let mut page = String::new();
            writeln!(page, "# {uncategorized_label}").unwrap();
            writeln!(page).unwrap();
            for entry in &ungrouped {
                let summary = extract(&entry.body).unwrap_or_default();
                if summary.is_empty() {
                    writeln!(page, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(page, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
            sub_pages.push((format!("{}/index/{slug}.md", dirs.wiki), page));
        }
    } else {
        for (group, group_entries) in &by_group {
            writeln!(out).unwrap();
            writeln!(out, "### {group} ({})", group_entries.len()).unwrap();
            writeln!(out).unwrap();
            for entry in group_entries {
                let summary = extract(&entry.body).unwrap_or_default();
                if summary.is_empty() {
                    writeln!(out, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(out, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
        }
        if !ungrouped.is_empty() {
            writeln!(out).unwrap();
            writeln!(out, "### {uncategorized_label} ({})", ungrouped.len()).unwrap();
            writeln!(out).unwrap();
            for entry in &ungrouped {
                let summary = extract(&entry.body).unwrap_or_default();
                if summary.is_empty() {
                    writeln!(out, "- [[{}]]", entry.link_target).unwrap();
                } else {
                    writeln!(out, "- [[{}]] — {}", entry.link_target, summary).unwrap();
                }
            }
        }
    }
}

/// Return the first non-blank, non-`#`-heading line that sits between `## {heading}`
/// and the next `## ` line. Used for concept (`## 핵심`) and document (`## 요약`)
/// summaries.
///
/// Heading match is exact (no leading/trailing whitespace before `##`). Returns `None`
/// if the heading isn't present or has no non-blank content before the next section.
pub fn first_line_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        // Next section header ends the search.
        if trimmed.starts_with("## ") {
            return None;
        }
        let content = trimmed.trim();
        if content.is_empty() {
            continue;
        }
        // Skip sub-headings (`### `, `#### `, …) and continue looking for the first
        // body line of the section.
        if content.starts_with('#') {
            continue;
        }
        return Some(content.to_string());
    }
    None
}

/// Like [`first_line_under_heading`] but specifically extracts the first list bullet
/// (`- `) underneath the section. Used by daily pages, which always lead `## 요약`
/// with a bulleted summary.
fn first_bullet_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        if trimmed.starts_with("## ") {
            return None;
        }
        let content = trimmed.trim_start();
        if let Some(rest) = content.strip_prefix("- ") {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

/// Return the text of the first `### ` sub-heading that appears under `## {heading}`.
/// Used for work-log pages where the topic name is encoded as `### Topic`.
fn first_subheading_under_heading(body: &str, heading: &str) -> Option<String> {
    let target = format!("## {heading}");
    let mut in_section = false;
    for line in body.lines() {
        let trimmed = line.trim_end();
        if !in_section {
            if trimmed == target {
                in_section = true;
            }
            continue;
        }
        if trimmed.starts_with("## ") {
            return None;
        }
        if let Some(rest) = trimmed.trim_start().strip_prefix("### ") {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

/// Fallback extractor for synthesis pages: the first non-blank, non-heading body line.
fn first_non_blank_body_line(body: &str) -> Option<String> {
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with('#') {
            continue;
        }
        // Strip a leading list marker so the one-liner reads naturally.
        let trimmed = trimmed
            .strip_prefix("- ")
            .or_else(|| trimmed.strip_prefix("* "))
            .unwrap_or(trimmed);
        return Some(trimmed.to_string());
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_file(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    #[test]
    fn empty_vault_yields_header_only() {
        let tmp = TempDir::new().unwrap();
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.starts_with("# Wiki Index"));
        assert!(out.contains("0 pages"));
        // No category sections should be rendered.
        assert!(!out.contains("## 개념"));
        assert!(!out.contains("## 문서"));
    }

    #[test]
    fn concept_section_uses_korean_heading_extractor() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/agentic-ai.md",
            "---\nid: agentic-ai\ntitle: \"Agentic AI\"\n---\n\n# Agentic AI\n\n\
             ## 핵심\n\n자율적으로 도구를 사용하는 AI 에이전트 패러다임.\n\n## 관련\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("## 개념 (1)"));
        assert!(out.contains("[[agentic-ai|Agentic AI]]"));
        assert!(out.contains("자율적으로 도구를 사용하는 AI 에이전트 패러다임."));
    }

    #[test]
    fn english_locale_uses_summary_heading_for_documents() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/documents/whitepaper.md",
            "---\nid: whitepaper\ntitle: White Paper\n---\n\n# White Paper\n\n\
             ## Summary\n\nA short overview of the paper.\n\n## Content\n",
        );
        let out = build_index(tmp.path(), Locale::En, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("## Documents (1)"));
        assert!(out.contains("[[wiki/documents/whitepaper]]"));
        assert!(out.contains("A short overview of the paper."));
    }

    #[test]
    fn daily_section_is_grouped_by_source_id() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "daily/email-digest/2026-05-22.md",
            "---\nid: e-1\ntitle: Email\n---\n\n## 요약\n\n- 첫 번째 메일 요약\n- 두 번째\n",
        );
        write_file(
            tmp.path(),
            "daily/team-slack/2026-05-22.md",
            "---\nid: s-1\ntitle: Slack\n---\n\n## 요약\n\n- 슬랙 트렌드\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("## 일일 — email-digest (1)"));
        assert!(out.contains("## 일일 — team-slack (1)"));
        assert!(out.contains("[[daily/email-digest/2026-05-22]] — 첫 번째 메일 요약"));
        assert!(out.contains("[[daily/team-slack/2026-05-22]] — 슬랙 트렌드"));
    }

    #[test]
    fn worklog_uses_first_subheading() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "me/work-log/2026-05-22.md",
            "---\nid: w-1\ntitle: Work\n---\n\n## 주제별 요약\n\n### 태블로 MCP\n- 미팅\n\n### 다른 주제\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("## 업무 로그 (1)"));
        assert!(out.contains("[[me/work-log/2026-05-22]] — 태블로 MCP"));
    }

    #[test]
    fn exploration_section_uses_question_heading() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/explorations/api-replay.md",
            "---\nid: api-replay\ntitle: \"API Replay\"\n---\n\n# API Replay\n\n\
             ## 질문\n\nAPI 호출만으로 자동화 가능한가?\n\n## 종합\n\n가능하다.\n\n## 근거\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("## 탐구 (1)"));
        assert!(out.contains("[[wiki/explorations/api-replay]]"));
        assert!(out.contains("API 호출만으로 자동화 가능한가?"));
    }

    #[test]
    fn synthesis_section_merges_all_tiers() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "synthesis/weekly/2026-W21.md",
            "---\nid: w-syn\ntitle: Weekly\n---\n\n# Weekly\n\nThis week we focused on X.\n",
        );
        write_file(
            tmp.path(),
            "me/monthly/2026-05.md",
            "---\nid: m\ntitle: May\n---\n\n# May\n\nMay summary.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("## 종합 (2)"));
        assert!(out.contains("[[me/monthly/2026-05]] — May summary."));
        assert!(out.contains("[[synthesis/weekly/2026-W21]] — This week we focused on X."));
    }

    #[test]
    fn files_without_frontmatter_are_skipped() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/no-front.md",
            "# Title\n\n## 핵심\n\nSome content.\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/with-front.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nKept.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        // Only the frontmatter-bearing page should show up.
        assert!(out.contains("## 개념 (1)"));
        assert!(out.contains("[[with-front|X]] — Kept."));
        assert!(!out.contains("no-front"));
    }

    #[test]
    fn agents_md_and_existing_index_are_not_listed() {
        let tmp = TempDir::new().unwrap();
        // Pre-existing index and schema doc; should never appear in the new index.
        write_file(
            tmp.path(),
            "wiki/index.md",
            "---\nid: idx\n---\n\n# Old\n\n## 핵심\n\nOld body.\n",
        );
        write_file(
            tmp.path(),
            "wiki/AGENTS.md",
            "---\nid: a\n---\n\n# Agents\n",
        );
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nReal.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(!out.contains("Old body"));
        assert!(!out.contains("[[Agents]]"));
        assert!(out.contains("[[x|X]]"));
    }

    #[test]
    fn nested_pages_keep_their_subdirectory_in_path_and_link() {
        // A page nested under a group dir must keep its subdirectory — otherwise two
        // same-stem pages in different subdirs collide and links point at the wrong file.
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/documents/team-a/spec.md",
            "---\nid: a\n---\n\n## 핵심\n\nA spec.\n",
        );
        write_file(
            tmp.path(),
            "wiki/documents/team-b/spec.md",
            "---\nid: b\n---\n\n## 핵심\n\nB spec.\n",
        );
        let out = build_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .unwrap()
            .main;
        assert!(out.contains("[[wiki/documents/team-a/spec]]"), "got: {out}");
        assert!(out.contains("[[wiki/documents/team-b/spec]]"), "got: {out}");
    }

    #[test]
    fn first_line_under_heading_basic() {
        let body = "# Title\n\n## 요약\n\nFirst real line.\nSecond line.\n\n## 다음\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("First real line.".to_string())
        );
    }

    #[test]
    fn first_line_under_heading_returns_none_when_missing() {
        let body = "# Title\n\n## 다른\n\nbody\n";
        assert!(first_line_under_heading(body, "요약").is_none());
    }

    #[test]
    fn first_line_under_heading_stops_at_next_section() {
        let body = "## 요약\n\n## 다음\n\nThis is in next section.\n";
        assert!(first_line_under_heading(body, "요약").is_none());
    }

    #[test]
    fn first_line_under_heading_skips_blank_lines() {
        let body = "## 요약\n\n\n\nFinally some text.\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("Finally some text.".to_string())
        );
    }

    #[test]
    fn first_line_under_heading_skips_subheadings() {
        let body = "## 요약\n\n### subhead\n\nActual content.\n";
        assert_eq!(
            first_line_under_heading(body, "요약"),
            Some("Actual content.".to_string())
        );
    }

    #[test]
    fn first_bullet_under_heading_picks_first_bullet() {
        let body = "## 요약\n\n- One\n- Two\n\n## Next\n";
        assert_eq!(
            first_bullet_under_heading(body, "요약"),
            Some("One".to_string())
        );
    }

    #[tokio::test]
    async fn write_index_atomic_no_temp_leftover() {
        let tmp = TempDir::new().unwrap();
        write_file(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: \"X\"\n---\n\n## 핵심\n\nbody\n",
        );
        let path = write_index(tmp.path(), Locale::Ko, 0, &VaultDirs::default())
            .await
            .unwrap();
        assert!(path.ends_with("wiki/index.md"));
        let content = tokio::fs::read_to_string(&path).await.unwrap();
        assert!(content.contains("[[x|X]]"));

        // Ensure no `.index.md.*` temp leftovers in wiki/.
        let mut entries = tokio::fs::read_dir(tmp.path().join("wiki")).await.unwrap();
        while let Some(entry) = entries.next_entry().await.unwrap() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            assert!(!name.ends_with(".tmp"), "leftover temp file: {name}");
        }
    }

    #[test]
    fn custom_dirs_produce_correct_paths() {
        let tmp = TempDir::new().unwrap();
        let dirs = VaultDirs {
            wiki: "knowledge".into(),
            daily: "feed".into(),
            personal: "my-notes".into(),
            synthesis: "team-synth".into(),
            ..Default::default()
        };
        write_file(
            tmp.path(),
            "knowledge/concepts/llm-wiki.md",
            "---\nid: llm-wiki\ntitle: \"LLM Wiki\"\ncategory: ai\n---\n\n## Synthesis\n\nA wiki.\n",
        );
        write_file(
            tmp.path(),
            "feed/ai-news/2026-05-20.md",
            "---\nid: d1\ntitle: \"News\"\n---\n\n## Summary\n\nHeadlines.\n",
        );
        write_file(
            tmp.path(),
            "team-synth/weekly/2026-W21.md",
            "---\nid: ts\ntitle: \"W21\"\n---\n\n## Key Themes\n\nThemes.\n",
        );
        let out = build_index(tmp.path(), Locale::En, 0, &dirs).unwrap().main;
        assert!(out.contains("[[llm-wiki|LLM Wiki]]"));
        assert!(out.contains("[[feed/ai-news/2026-05-20]]"));
        assert!(out.contains("[[team-synth/weekly/2026-W21]]"));
        assert!(!out.contains("wiki/"));
        assert!(!out.contains("daily/"));
    }
}
