//! Wiki timeline (`log.md`) — a deterministic, reverse-chronological log of WHEN each
//! knowledge node first entered the vault.
//!
//! This is Karpathy's append-only `log.md`, realized the Lorekeeper way: a MATERIALIZED
//! VIEW, not a hand-appended file. It is regenerated from each page's frontmatter, so an
//! unchanged vault re-renders byte-identical (like `index.md`) and a re-run is a true
//! no-op — it can never drift, duplicate, or lose an entry. It complements `index.md`
//! (the by-topic catalog) with a by-time view: "what knowledge entered, and when?".
//!
//! Two deliberate design rules keep the signal meaningful:
//!
//! 1. **Anchored on `created` ONLY, never `updated`.** A concept's `updated` is its
//!    last-observation date — it churns every time the concept is re-mentioned, and
//!    machine work (ingest re-render, `backlinks-sync`) can touch it. Keying a knowledge
//!    timeline off `updated` would inject that churn as fake "knowledge changed" events.
//!    First-appearance (`created`) is the only stable, meaningful anchor.
//! 2. **Durable knowledge nodes only** — `{wiki}/concepts`, `{wiki}/documents`,
//!    `{wiki}/explorations`. Daily/synthesis pages are time-stamped operational records,
//!    not knowledge nodes. This is a principled classification, not a fuzzy
//!    importance/activity score (which would be a heuristic).
//!
//! The timeline is complete — every durable knowledge node ever created appears, exactly
//! as `index.md` catalogs every page. Both are text-only materialized views that grow
//! linearly in the number of nodes (a few hundred KB even after years), so neither
//! truncates; the long-term evolution of the vault is the whole point of a by-time view.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use lk_core::config::VaultDirs;
use lk_core::frontmatter::parse_page;
use lk_core::i18n::Locale;
use lk_core::vault_path::{concepts_dir, documents_dir, explorations_dir};
use walkdir::WalkDir;

use crate::VaultError;
use crate::writer::VaultWriter;

struct TimelineEntry {
    /// When the node first entered the vault (frontmatter `created`) — the timeline anchor.
    created: jiff::civil::Date,
    /// Vault-relative page path — the link destination is computed from it, relative
    /// to the timeline's own location (`{wiki}/log.md`).
    path: std::path::PathBuf,
    /// Display title.
    title: String,
}

/// Build the `log.md` body: a reverse-chronological knowledge timeline for the vault at
/// `vault_root`, covering every durable knowledge node. A pure function of on-disk
/// frontmatter — re-running on an unchanged vault yields identical bytes. Pages missing
/// a parseable `created` date are skipped (they have no place on a timeline), never guessed.
pub fn build_timeline(
    vault_root: &Path,
    locale: Locale,
    dirs: &VaultDirs,
) -> Result<String, VaultError> {
    let mut entries: Vec<TimelineEntry> = Vec::new();
    let mut seen: HashSet<PathBuf> = HashSet::new();
    for dir in [
        concepts_dir(dirs),
        documents_dir(dirs),
        explorations_dir(dirs),
    ] {
        collect_into(&mut entries, vault_root, &dir, &mut seen);
    }

    // Group by created date. BTreeMap keeps dates ascending; we emit descending so the
    // newest knowledge is first. Within a date, entries sort by title then id — a stable,
    // deterministic render.
    let shown = entries.len();
    let mut by_date: BTreeMap<jiff::civil::Date, Vec<TimelineEntry>> = BTreeMap::new();
    for e in entries {
        by_date.entry(e.created).or_default().push(e);
    }

    // Every entry destination is relative to the timeline's own location.
    let log_rel = Path::new(&dirs.wiki).join(lk_core::vault_path::TIMELINE_FILE);

    let mut out = String::new();
    writeln!(out, "# {}", locale.strings().log_title).unwrap();
    writeln!(out).unwrap();
    // No timestamp: a deterministic function of vault content, so an unchanged vault
    // re-renders byte-identical and a re-run is a true no-op.
    writeln!(out, "> Generated by `lore wiki log` — {shown} entries.").unwrap();

    for (date, mut day_entries) in by_date.into_iter().rev() {
        day_entries.sort_by(|a, b| a.title.cmp(&b.title).then_with(|| a.path.cmp(&b.path)));
        writeln!(out).unwrap();
        writeln!(out, "## {date}").unwrap();
        writeln!(out).unwrap();
        for e in day_entries {
            let dest = lk_core::link::relative_dest(&log_rel, &e.path);
            writeln!(out, "- {}", lk_core::link::md_link(&e.title, &dest)).unwrap();
        }
    }

    Ok(out)
}

/// Build the timeline and atomically write it to `{wiki}/log.md`. Returns the
/// vault-relative path written.
pub fn write_timeline(
    vault_root: &Path,
    locale: Locale,
    dirs: &VaultDirs,
) -> Result<std::path::PathBuf, VaultError> {
    let content = build_timeline(vault_root, locale, dirs)?;
    let rel = Path::new(&dirs.wiki).join(lk_core::vault_path::TIMELINE_FILE);
    VaultWriter::new(vault_root).write_generated_page_sync(&rel, &content)?;
    // Return the absolute path, matching `write_index`, so every `lore wiki` command
    // reports the file it wrote uniformly.
    Ok(vault_root.join(rel))
}

/// The page formats this timeline is a timeline OF — one per directory it walks. A subset of
/// [`lk_core::vault_path::PAGE_FORMATS`], asserted so a typo here cannot silently drop a whole
/// format off the timeline.
const KNOWLEDGE_FORMATS: &[&str] = &["concept", "document", "exploration"];

/// Walk one knowledge directory, parsing each page's `created`/`title` into a [`TimelineEntry`].
/// Unreadable or undated pages are skipped — never guessed onto the timeline.
///
/// `seen` carries canonical page identity across the three directories. All three sit under
/// `wiki`, which reads like enough — but a `vault.dirs` root the filesystem folds onto another
/// puts a daily page inside one of them, and the timeline promises durable knowledge nodes
/// only. It was reached that way: a daily digest became a permanent entry in the knowledge
/// timeline, which is the one thing this file says it will not do.
fn collect_into(
    entries: &mut Vec<TimelineEntry>,
    vault_root: &Path,
    rel_dir: &Path,
    seen: &mut HashSet<PathBuf>,
) {
    let abs = vault_root.join(rel_dir);
    if !abs.is_dir() {
        return;
    }
    for dirent in WalkDir::new(&abs).into_iter().flatten() {
        if !dirent.file_type().is_file() {
            continue;
        }
        let path = dirent.path();
        if !seen.insert(std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())) {
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let Ok(raw) = std::fs::read_to_string(path) else {
            continue;
        };
        let Ok(page) = parse_page(&raw) else {
            continue;
        };
        // The three directories walked here hold the three durable knowledge formats, and a
        // page declaring any other one is foreign to them however it arrived — a `vault.dirs`
        // root the filesystem folds onto another lands a daily digest inside `wiki/concepts`,
        // and this file promises knowledge nodes only. Directory membership was the whole test
        // before, which made that promise depend on nothing checkable. A page declaring no
        // type at all predates the field and stays: the check names what is foreign, not what
        // is permitted.
        if page
            .frontmatter
            .get("type")
            .and_then(|value| value.as_str())
            .is_some_and(|declared| !KNOWLEDGE_FORMATS.contains(&declared))
        {
            continue;
        }
        let Some(created) = fm_date(&page, "created") else {
            continue;
        };
        let rel = path.strip_prefix(vault_root).unwrap_or(path);
        let title = page
            .frontmatter
            .get("title")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .map(str::to_owned)
            .unwrap_or_else(|| {
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("untitled")
                    .to_owned()
            });
        entries.push(TimelineEntry {
            created,
            path: rel.to_path_buf(),
            title,
        });
    }
}

fn fm_date(page: &lk_core::frontmatter::VaultPage, key: &str) -> Option<jiff::civil::Date> {
    page.frontmatter
        .get(key)
        .and_then(|v| v.as_str())
        .and_then(|s| s.parse::<jiff::civil::Date>().ok())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Which formats are durable knowledge is a judgement this file makes, but that they are
    /// formats this tool writes at all is not — and a typo here does not fail anything on its
    /// own. It reads as "no page of that format is a knowledge node", so the whole format drops
    /// off the timeline silently.
    #[test]
    fn every_knowledge_format_is_a_format_this_tool_writes() {
        for format in KNOWLEDGE_FORMATS {
            assert!(
                lk_core::vault_path::PAGE_FORMATS.contains(format),
                "{format:?} is not a page format Lorekeeper writes"
            );
        }
    }

    fn write(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(p, body).unwrap();
    }

    fn concept(root: &Path, slug: &str, title: &str, created: &str) {
        write(
            root,
            &format!("wiki/concepts/{slug}.md"),
            &format!("---\nid: {slug}\ntitle: {title}\ncreated: {created}\n---\n"),
        );
    }

    /// The timeline is a timeline of durable knowledge, and directory membership was the whole
    /// test — so an operational record that landed in one of these directories became a
    /// permanent knowledge entry. It lands there when a `vault.dirs` root the filesystem folds
    /// puts `<daily>` inside `wiki`. A page declaring no type predates the field and stays,
    /// since the check names what is foreign rather than what is permitted.
    #[test]
    fn an_operational_record_inside_a_knowledge_directory_is_not_a_knowledge_node() {
        let tmp = TempDir::new().unwrap();
        write(
            tmp.path(),
            "wiki/concepts/2026-02-10.md",
            "---\nid: d\ntype: daily\ntitle: Digest\ncreated: 2026-02-10\n---\n",
        );
        write(
            tmp.path(),
            "wiki/concepts/rag.md",
            "---\nid: rag\ntype: concept\ntitle: RAG\ncreated: 2026-02-11\n---\n",
        );
        // No `type` at all: a page from before the field, which must not be dropped.
        write(
            tmp.path(),
            "wiki/documents/old.md",
            "---\nid: old\ntitle: Old\ncreated: 2026-02-12\n---\n",
        );

        let out = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(
            !out.contains("Digest"),
            "a daily record is not knowledge:\n{out}"
        );
        assert!(out.contains("RAG"), "{out}");
        assert!(out.contains("Old"), "an untyped page stays:\n{out}");
    }

    #[test]
    fn timeline_is_reverse_chronological_and_navigable() {
        let tmp = TempDir::new().unwrap();
        let dirs = VaultDirs::default();
        concept(tmp.path(), "rag", "RAG", "2026-05-20");
        concept(tmp.path(), "embeddings", "Embeddings", "2026-05-22");
        write(
            tmp.path(),
            "wiki/documents/report.md",
            "---\nid: report\ntitle: Report\ncreated: 2026-05-20\n---\n",
        );

        let out = build_timeline(tmp.path(), Locale::Ko, &dirs).unwrap();
        let h22 = out.find("## 2026-05-22").unwrap();
        let h20 = out.find("## 2026-05-20").unwrap();
        assert!(h22 < h20, "newer date must come first:\n{out}");
        assert!(out.contains("3 entries"));
        assert!(out.contains("- [Embeddings](concepts/embeddings.md)"));
        assert!(out.contains("- [Report](documents/report.md)"));
    }

    #[test]
    fn timeline_anchors_on_created_not_updated() {
        // `updated` churn (re-mention / machine re-render) must NOT move an entry or add
        // a noise annotation — the timeline is keyed on first-appearance only.
        let tmp = TempDir::new().unwrap();
        write(
            tmp.path(),
            "wiki/concepts/rag.md",
            "---\nid: rag\ntitle: RAG\ncreated: 2026-05-20\nupdated: 2026-09-01\n---\n",
        );
        let out = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("## 2026-05-20"), "must be placed by created");
        assert!(
            !out.contains("2026-09-01"),
            "updated must not appear anywhere"
        );
        assert!(!out.contains("updated"), "no updated annotation");
    }

    #[test]
    fn timeline_is_complete_regardless_of_age() {
        // Every durable knowledge node appears, however old — the timeline is a complete
        // by-time view (as `index.md` is a complete by-topic view), never truncated. The
        // long-term evolution of the vault is exactly what this view exists to show.
        let tmp = TempDir::new().unwrap();
        concept(tmp.path(), "ancient", "Ancient", "2020-01-01");
        concept(tmp.path(), "recent", "Recent", "2026-05-20");
        let out = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("[Recent]("), "recent entry shown");
        assert!(
            out.contains("[Ancient]("),
            "years-old entry shown — never truncated"
        );
        assert!(out.contains("2 entries"));
        // Newest date first, oldest last — reverse chronological across any span.
        let h_recent = out.find("## 2026-05-20").unwrap();
        let h_ancient = out.find("## 2020-01-01").unwrap();
        assert!(h_recent < h_ancient, "reverse chronological:\n{out}");
    }

    #[test]
    fn undated_pages_skipped_and_render_is_deterministic() {
        let tmp = TempDir::new().unwrap();
        write(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: X\n---\n",
        ); // no created
        concept(tmp.path(), "y", "Y", "2026-05-20");
        let first = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        let second = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert_eq!(first, second, "build must be deterministic");
        assert!(first.contains("1 entries"));
        assert!(!first.contains("[X]("), "undated page must be skipped");
    }

    #[test]
    fn empty_vault_yields_just_the_header() {
        let tmp = TempDir::new().unwrap();
        let out = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(out.contains("# 지식 로그"));
        assert!(out.contains("0 entries"));
    }

    /// The returned path is what `lore wiki log` prints as the file it wrote, so it has to be
    /// that file: the timeline landing somewhere else while the command reported success is
    /// indistinguishable from working, and the reserved name is what the graph excludes.
    #[test]
    fn the_timeline_is_written_where_the_returned_path_says() {
        let tmp = TempDir::new().unwrap();
        let dirs = VaultDirs::default();
        concept(tmp.path(), "y", "Y", "2026-05-20");

        let written = write_timeline(tmp.path(), Locale::Ko, &dirs).unwrap();
        assert_eq!(
            written,
            tmp.path()
                .join(&dirs.wiki)
                .join(lk_core::vault_path::TIMELINE_FILE)
        );
        assert_eq!(
            std::fs::read_to_string(&written).unwrap(),
            build_timeline(tmp.path(), Locale::Ko, &dirs).unwrap()
        );
    }

    #[test]
    fn timeline_h1_is_localized() {
        let tmp = TempDir::new().unwrap();
        let en = build_timeline(tmp.path(), Locale::En, &VaultDirs::default()).unwrap();
        assert!(en.contains("# Knowledge Log"), "EN H1 localized:\n{en}");
        let ko = build_timeline(tmp.path(), Locale::Ko, &VaultDirs::default()).unwrap();
        assert!(ko.contains("# 지식 로그"), "KO H1 localized:\n{ko}");
    }
}
