//! Wiki timeline (`log.md`) — a deterministic, reverse-chronological log of WHEN each
//! knowledge node first entered the vault.
//!
//! This is Karpathy's append-only `log.md`, realized the Lorekeeper way: a MATERIALIZED
//! VIEW, not a hand-appended file. It is regenerated from each page's frontmatter, so an
//! unchanged vault re-renders byte-identical (like `index.md`) and a re-run is a true
//! no-op — it can never drift, duplicate, or lose an entry. It complements `index.md`
//! (the by-topic catalog) with a by-time view: "what knowledge entered, and when?".
//!
//! Three deliberate design rules keep the signal meaningful and the page bounded:
//!
//! 1. **Anchored on `created` ONLY, never `updated`.** A concept's `updated` is its
//!    last-observation date — it churns every time the concept is re-mentioned, and
//!    machine work (ingest re-render, `backlinks-sync`) can touch it. Keying a knowledge
//!    timeline off `updated` would inject that churn as fake "knowledge changed" events.
//!    First-appearance (`created`) is the only stable, meaningful anchor.
//! 2. **Durable knowledge nodes only** — `{wiki}/concepts`, `{wiki}/documents`,
//!    `{wiki}/explorations`. Daily/synthesis pages are time-stamped operational records,
//!    not knowledge nodes. This is a principled classification, not a fuzzy
//!    importance/activity score (which would be a heuristic).
//! 3. **Bounded to a rolling window.** A multi-year vault would otherwise grow `log.md`
//!    without limit (one entry per knowledge page ever), violating the scalability
//!    principle. The page shows only entries within [`TIMELINE_WINDOW_DAYS`] of the most
//!    recent entry — relative to the newest *entry* (not the wall clock) so the build
//!    stays a deterministic function of vault content. Older history is never lost: it
//!    lives on each page's own `created` frontmatter (the source of truth) and in git.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use lk_core::config::VaultDirs;
use lk_core::frontmatter::parse_page;
use walkdir::WalkDir;

use crate::VaultError;
use crate::writer::VaultWriter;

/// Rolling window (in days, relative to the newest entry) that `log.md` covers. Bounds
/// the page to roughly one year of knowledge activity regardless of how old the vault is.
const TIMELINE_WINDOW_DAYS: i64 = 365;

struct Entry {
    /// When the node first entered the vault (frontmatter `created`) — the timeline anchor.
    created: jiff::civil::Date,
    /// Vault-relative wikilink target (path form, without `.md`) — always resolves.
    id: String,
    /// Display title.
    title: String,
}

/// Build the `log.md` body: a reverse-chronological knowledge timeline for the vault at
/// `vault_root`, bounded to the most recent `TIMELINE_WINDOW_DAYS`. A pure function of
/// on-disk frontmatter — re-running on an unchanged vault yields identical bytes. Pages
/// missing a parseable `created` date are skipped (they have no place on a timeline),
/// never guessed.
pub fn build_timeline(vault_root: &Path, dirs: &VaultDirs) -> Result<String, VaultError> {
    let wiki = Path::new(&dirs.wiki);
    let mut entries: Vec<Entry> = Vec::new();
    for sub in ["concepts", "documents", "explorations"] {
        collect_into(&mut entries, vault_root, &wiki.join(sub));
    }

    // Bound to the rolling window, measured from the newest entry (not the wall clock,
    // which would make the build non-deterministic). Older entries stay on their pages.
    if let Some(newest) = entries.iter().map(|e| e.created).max() {
        let cutoff = newest
            .checked_sub(jiff::Span::new().days(TIMELINE_WINDOW_DAYS))
            .unwrap_or(jiff::civil::Date::MIN);
        entries.retain(|e| e.created >= cutoff);
    }

    // Group by created date. BTreeMap keeps dates ascending; we emit descending so the
    // newest knowledge is first. Within a date, entries sort by title then id — a stable,
    // deterministic render.
    let shown = entries.len();
    let mut by_date: BTreeMap<jiff::civil::Date, Vec<Entry>> = BTreeMap::new();
    for e in entries {
        by_date.entry(e.created).or_default().push(e);
    }

    let mut out = String::new();
    writeln!(out, "# Knowledge Log").unwrap();
    writeln!(out).unwrap();
    // No timestamp: a deterministic function of vault content, so an unchanged vault
    // re-renders byte-identical and a re-run is a true no-op.
    writeln!(
        out,
        "> Generated by `lore wiki log` — {shown} entries in the last {TIMELINE_WINDOW_DAYS} days. \
         Older history lives on each page's `created` frontmatter."
    )
    .unwrap();

    for (date, mut day_entries) in by_date.into_iter().rev() {
        day_entries.sort_by(|a, b| a.title.cmp(&b.title).then_with(|| a.id.cmp(&b.id)));
        writeln!(out).unwrap();
        writeln!(out, "## {date}").unwrap();
        writeln!(out).unwrap();
        for e in day_entries {
            writeln!(out, "- [[{}|{}]]", e.id, e.title).unwrap();
        }
    }

    Ok(out)
}

/// Build the timeline and atomically write it to `{wiki}/log.md`. Returns the
/// vault-relative path written.
pub fn write_timeline(
    vault_root: &Path,
    dirs: &VaultDirs,
) -> Result<std::path::PathBuf, VaultError> {
    let content = build_timeline(vault_root, dirs)?;
    let rel = Path::new(&dirs.wiki).join("log.md");
    VaultWriter::new(vault_root).write_page_sync(&rel, &content)?;
    Ok(rel)
}

/// Walk one knowledge directory, parsing each page's `created`/`title` into an [`Entry`].
/// Unreadable or undated pages are skipped — never guessed onto the timeline.
fn collect_into(entries: &mut Vec<Entry>, vault_root: &Path, rel_dir: &Path) {
    let abs = vault_root.join(rel_dir);
    if !abs.is_dir() {
        return;
    }
    for dirent in WalkDir::new(&abs).into_iter().flatten() {
        if !dirent.file_type().is_file() {
            continue;
        }
        let path = dirent.path();
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let Ok(raw) = std::fs::read_to_string(path) else {
            continue;
        };
        let Ok(page) = parse_page(&raw) else {
            continue;
        };
        let Some(created) = fm_date(&page, "created") else {
            continue;
        };
        let rel = path.strip_prefix(vault_root).unwrap_or(path);
        let id = rel.with_extension("").to_string_lossy().replace('\\', "/");
        let title = page
            .frontmatter
            .get("title")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .map(str::to_owned)
            .unwrap_or_else(|| {
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("untitled")
                    .to_owned()
            });
        entries.push(Entry { created, id, title });
    }
}

fn fm_date(page: &lk_core::frontmatter::VaultPage, key: &str) -> Option<jiff::civil::Date> {
    page.frontmatter
        .get(key)
        .and_then(|v| v.as_str())
        .and_then(|s| s.parse::<jiff::civil::Date>().ok())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(p, body).unwrap();
    }

    fn concept(root: &Path, slug: &str, title: &str, created: &str) {
        write(
            root,
            &format!("wiki/concepts/{slug}.md"),
            &format!("---\nid: {slug}\ntitle: {title}\ncreated: {created}\n---\n"),
        );
    }

    #[test]
    fn timeline_is_reverse_chronological_and_navigable() {
        let tmp = TempDir::new().unwrap();
        let dirs = VaultDirs::default();
        concept(tmp.path(), "rag", "RAG", "2026-05-20");
        concept(tmp.path(), "embeddings", "Embeddings", "2026-05-22");
        write(
            tmp.path(),
            "wiki/documents/report.md",
            "---\nid: report\ntitle: Report\ncreated: 2026-05-20\n---\n",
        );

        let out = build_timeline(tmp.path(), &dirs).unwrap();
        let h22 = out.find("## 2026-05-22").unwrap();
        let h20 = out.find("## 2026-05-20").unwrap();
        assert!(h22 < h20, "newer date must come first:\n{out}");
        assert!(out.contains("3 entries"));
        assert!(out.contains("- [[wiki/concepts/embeddings|Embeddings]]"));
        assert!(out.contains("- [[wiki/documents/report|Report]]"));
    }

    #[test]
    fn timeline_anchors_on_created_not_updated() {
        // `updated` churn (re-mention / machine re-render) must NOT move an entry or add
        // a noise annotation — the timeline is keyed on first-appearance only.
        let tmp = TempDir::new().unwrap();
        write(
            tmp.path(),
            "wiki/concepts/rag.md",
            "---\nid: rag\ntitle: RAG\ncreated: 2026-05-20\nupdated: 2026-09-01\n---\n",
        );
        let out = build_timeline(tmp.path(), &VaultDirs::default()).unwrap();
        assert!(out.contains("## 2026-05-20"), "must be placed by created");
        assert!(
            !out.contains("2026-09-01"),
            "updated must not appear anywhere"
        );
        assert!(!out.contains("updated"), "no updated annotation");
    }

    #[test]
    fn timeline_is_bounded_to_recent_window() {
        // An old entry far outside the window (relative to the newest entry) is excluded,
        // so the page can't grow without bound as the vault ages.
        let tmp = TempDir::new().unwrap();
        concept(tmp.path(), "ancient", "Ancient", "2020-01-01");
        concept(tmp.path(), "recent", "Recent", "2026-05-20");
        let out = build_timeline(tmp.path(), &VaultDirs::default()).unwrap();
        assert!(out.contains("|Recent]]"), "recent entry shown");
        assert!(
            !out.contains("|Ancient]]"),
            "out-of-window entry bounded out"
        );
        assert!(out.contains("1 entries"));
        // The boundary is relative to the newest entry, not the wall clock: two entries
        // both old but within a year of each other are both shown.
        let tmp2 = TempDir::new().unwrap();
        concept(tmp2.path(), "a", "A", "2020-01-01");
        concept(tmp2.path(), "b", "B", "2020-06-01");
        let out2 = build_timeline(tmp2.path(), &VaultDirs::default()).unwrap();
        assert!(
            out2.contains("|A]]") && out2.contains("|B]]"),
            "both within window:\n{out2}"
        );
    }

    #[test]
    fn undated_pages_skipped_and_render_is_deterministic() {
        let tmp = TempDir::new().unwrap();
        write(
            tmp.path(),
            "wiki/concepts/x.md",
            "---\nid: x\ntitle: X\n---\n",
        ); // no created
        concept(tmp.path(), "y", "Y", "2026-05-20");
        let first = build_timeline(tmp.path(), &VaultDirs::default()).unwrap();
        let second = build_timeline(tmp.path(), &VaultDirs::default()).unwrap();
        assert_eq!(first, second, "build must be deterministic");
        assert!(first.contains("1 entries"));
        assert!(!first.contains("|X]]"), "undated page must be skipped");
    }

    #[test]
    fn empty_vault_yields_just_the_header() {
        let tmp = TempDir::new().unwrap();
        let out = build_timeline(tmp.path(), &VaultDirs::default()).unwrap();
        assert!(out.contains("# Knowledge Log"));
        assert!(out.contains("0 entries"));
    }
}
