//! Re-derive each concept page's `## <Sources>` body AND its frontmatter
//! `source_count` from the actual link graph — this module is the single
//! source-of-truth for both. Ingest writes neither: it renders the Sources heading
//! empty and preserves the on-disk `source_count` verbatim (0 for a new page), so this
//! sync is what makes them correct: every daily/work-log/etc. page that links the concept
//! becomes a `- [title](relative-path)` entry, and the count is that entry total. Manual
//! edits (a daily page gains/loses a concept link) and source-page deletions are
//! reflected on the next run.
//!
//! Pure set comparison: no heuristics, no LLM, no per-source rules. A page is in
//! the sources list iff it has an outgoing link that resolves to the concept.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::{Path, PathBuf};

use lk_core::config::VaultDirs;
use lk_core::frontmatter;
use lk_core::i18n::Locale;
use lk_core::link;
use lk_vault::{VaultWriter, replace_section, section_body, set_frontmatter_field};
use serde::Serialize;

use crate::GraphError;
use crate::scan::{ScannedPage, VaultExistence, is_concept_page, is_valid_source, path_slug};

/// Outcome of one concept page's reconciliation.
#[derive(Debug, Clone, Serialize)]
pub struct ConceptUpdate {
    /// Vault-relative path of the concept page that was (or would be) updated.
    pub path: PathBuf,
    /// Sources that were missing from the page and would be added.
    pub added: Vec<String>,
    /// Sources that were on the page but no longer have an incoming link.
    pub removed: Vec<String>,
}

/// Outcome of a backlinks-sync run (a mutating operation), mirroring `MergeResult`:
/// domain-module operation outcomes are `*Result`; the CLI presentation wrapper is
/// `output::BacklinksSyncReport`.
#[derive(Debug, Default, Serialize)]
pub struct BacklinksSyncResult {
    /// Concept pages whose sources section differed and was rewritten (or would be,
    /// under `--dry-run`).
    pub updated: Vec<ConceptUpdate>,
    /// Count of concept pages whose existing sources section was already correct.
    pub unchanged: usize,
    /// Concept pages that could not record `source_count` because they carry no frontmatter
    /// block. Reported rather than silently skipped — their citation counts are stale until
    /// a human gives them frontmatter — and the command exits non-zero while any remain.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub skipped: Vec<PathBuf>,
    /// Whether this was a dry run (no writes were performed).
    pub dry_run: bool,
}

/// Recompute the `## <Sources>` section on every `{wiki}/concepts/{slug}.md` page from
/// the incoming links observed in `pages`, and rewrite any page whose section
/// differs. Returns the diff per page plus a count of pages that needed no change.
///
/// `dry_run = true` skips all writes but still reports what would change. Re-running
/// the command after a real run is a no-op: the sources block is generated by the
/// same routine that compares against it.
pub fn sync_concept_backlinks(
    pages: &[ScannedPage],
    vault_root: &Path,
    locale: Locale,
    dry_run: bool,
    dirs: &VaultDirs,
) -> Result<BacklinksSyncResult, GraphError> {
    // Reverse index: concept page id → sorted set of source page ids that cite it.
    // `outgoing` targets are already resolved page ids (scan resolves each destination
    // against its page's location), so crediting is a set-membership check — `## Sources`
    // and `source_count` can never diverge from the link graph. Only non-concept content
    // pages count as sources (`is_valid_source`); a concept→concept link belongs in
    // `## Related`, and navigation pages aren't sources. BTreeMap/BTreeSet keep the
    // rendered body deterministic.
    // `pages` here is a full-vault scan of every page dir, so it IS the vault.
    let existence = VaultExistence::build(pages, dirs);
    let by_id: HashMap<&str, &ScannedPage> = pages.iter().map(|p| (p.id.as_str(), p)).collect();
    let mut incoming: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for page in pages {
        if !is_valid_source(&page.path, dirs) {
            continue;
        }
        for target in &page.outgoing {
            // Self-references are excluded for the same reason the graph excludes
            // self-edges.
            if *target != page.id && existence.is_knowledge(target) {
                incoming
                    .entry(target.clone())
                    .or_default()
                    .insert(page.id.clone());
            }
        }
    }

    let writer = VaultWriter::new(vault_root);
    let mut report = BacklinksSyncResult {
        dry_run,
        ..BacklinksSyncResult::default()
    };

    for page in pages {
        if !is_concept_page(&page.path, dirs) {
            continue;
        }

        if page.id.is_empty() {
            continue;
        }

        // Sources for this concept = every page that links it.
        let mut sources: Vec<String> = incoming
            .get(&page.id)
            .map(|set| set.iter().cloned().collect())
            .unwrap_or_default();
        sources.sort();

        let full_path = vault_root.join(&page.path);
        let raw = std::fs::read_to_string(&full_path)
            .map_err(|e| GraphError::Io(format!("failed to read {}: {e}", full_path.display())))?;

        // Find the existing Sources heading under ANY locale (a page authored before a
        // `vault.locale` switch keeps its old-language heading), then rewrite under it —
        // mirrors the pipeline's all-locale `capture_section`. New pages with no such
        // section fall back to the current locale's heading.
        let heading = Locale::ALL
            .iter()
            .map(|l| l.strings().concept_sources)
            .find(|h| section_body(&raw, h).is_some())
            .unwrap_or_else(|| locale.strings().concept_sources);

        let existing = parse_existing_sources(&raw, heading, &page.path);
        let existing_set: BTreeSet<&str> = existing.iter().map(String::as_str).collect();
        let desired_set: BTreeSet<&str> = sources.iter().map(String::as_str).collect();

        // `source_count` frontmatter is re-derived here too (ingest preserves the
        // on-disk value but never computes it): the authoritative count is the number
        // of incoming citations, the same set that drives the `## Sources` body.
        // The page was read successfully above; a frontmatter that won't parse here is
        // real corruption, and this branch is about to REWRITE the page — silently
        // treating the count as 0 would reset a valid count from a transient parse glitch.
        // A simply-absent `source_count` field is the legitimate new-page case → 0.
        let existing_count = frontmatter::parse_page(&raw)
            .map_err(|e| {
                GraphError::Io(format!(
                    "failed to parse frontmatter of {}: {e}",
                    full_path.display()
                ))
            })?
            .frontmatter
            .source_count()
            .unwrap_or(0);
        let desired_count = sources.len() as u64;

        if existing_set == desired_set && existing_count == desired_count {
            report.unchanged += 1;
            continue;
        }

        let added: Vec<String> = desired_set
            .difference(&existing_set)
            .map(|s| (*s).to_owned())
            .collect();
        let removed: Vec<String> = existing_set
            .difference(&desired_set)
            .map(|s| (*s).to_owned())
            .collect();

        let new_body = render_sources_body(&sources, &page.path, &by_id);
        // A page with no frontmatter block (hand-created in Obsidian, say) has nowhere to
        // record the count. That is this page's defect, not the sweep's: aborting here would
        // leave the pages already written synced and every page after it not, and one such
        // page would block the janitor forever. It is recorded and skipped, and the command
        // still exits non-zero.
        let Some(updated_content) =
            set_source_count(&replace_section(&raw, heading, &new_body), desired_count)
        else {
            report.skipped.push(page.path.clone());
            continue;
        };

        if !dry_run && updated_content != raw {
            writer
                .write_page_sync(&page.path, &updated_content)
                .map_err(|e| {
                    GraphError::Io(format!("failed to write {}: {e}", page.path.display()))
                })?;
        }

        report.updated.push(ConceptUpdate {
            path: page.path.clone(),
            added,
            removed,
        });
    }

    Ok(report)
}

/// Extract the resolved page ids of the links in the existing `## <heading>` section,
/// in their on-disk order. Used only to compute the diff (added/removed) — the
/// rewritten body is canonicalised through [`render_sources_body`].
pub(crate) fn parse_existing_sources(
    content: &str,
    heading: &str,
    concept_path: &Path,
) -> Vec<String> {
    // Read the section body through the same fence-aware boundary `replace_section`
    // rewrites against, so the diff and the rewrite never disagree about where the
    // section ends (a fenced `## ` inside the body is content, not a boundary).
    let Some(body) = section_body(content, heading) else {
        return Vec::new();
    };

    link::extract_dests(body)
        .into_iter()
        .filter_map(|dest| link::resolve_dest(concept_path, &dest))
        .map(|resolved| path_slug(&resolved))
        .filter(|id| !id.is_empty())
        .collect()
}

/// Set the frontmatter `source_count` — a thin wrapper over the single-sourced
/// `set_frontmatter_field` so backlinks and the audit marker share one writer.
fn set_source_count(content: &str, count: u64) -> Option<String> {
    set_frontmatter_field(
        content,
        frontmatter::field::SOURCE_COUNT,
        &count.to_string(),
    )
}

/// Render the sources list: `- [title](relative-path)` per line, newline-separated,
/// no trailing newline (the section helper owns separators). Each destination is
/// relative to the concept page's own directory, the address form every emitter
/// writes; the display text is the source page's title.
pub(crate) fn render_sources_body(
    sources: &[String],
    concept_path: &Path,
    by_id: &HashMap<&str, &ScannedPage>,
) -> String {
    sources
        .iter()
        .map(|id| {
            let (title, dest) = match by_id.get(id.as_str()) {
                Some(source) => (
                    source.title.as_str(),
                    link::relative_dest(concept_path, &source.path),
                ),
                // A source id always comes from the same scan `by_id` was built from,
                // so this arm is unreachable in practice; addressing by id keeps the
                // entry meaningful if it ever isn't.
                None => (id.as_str(), link::encode_dest(&format!("/{id}.md"))),
            };
            format!("- {}", link::md_link(title, &dest))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn build_page(id: &str, rel: &str, outgoing: &[&str]) -> ScannedPage {
        ScannedPage {
            id: id.to_owned(),
            path: PathBuf::from(rel),
            title: id.to_owned(),
            outgoing: outgoing.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    fn write_concept(dir: &TempDir, stem: &str, source_lines: &[&str]) {
        let path = dir.path().join("wiki/concepts").join(format!("{stem}.md"));
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let count = source_lines.len();
        let body = if source_lines.is_empty() {
            format!(
                "---\nid: {stem}\nsource_count: {count}\n---\n\n# {stem}\n\n## 출처\n\n\n## 메타\n\n- key: value\n"
            )
        } else {
            format!(
                "---\nid: {stem}\nsource_count: {count}\n---\n\n# {stem}\n\n## 출처\n\n{}\n\n## 메타\n\n- key: value\n",
                source_lines.join("\n")
            )
        };
        std::fs::write(&path, body).unwrap();
    }

    #[test]
    fn inserts_missing_backlink() {
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);

        let pages = vec![
            build_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            // A daily page that links the concept.
            build_page(
                "daily/slack/2026-05-20",
                "daily/slack/2026-05-20.md",
                &["wiki/concepts/oy365"],
            ),
        ];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 1);
        assert_eq!(report.unchanged, 0);
        assert_eq!(report.updated[0].added, vec!["daily/slack/2026-05-20"]);
        assert!(report.updated[0].removed.is_empty());

        // The entry links the source page relative to the concept's own directory,
        // titled by the source page's title.
        let content = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();
        assert!(content.contains(
            "## 출처\n\n- [daily/slack/2026-05-20](../../daily/slack/2026-05-20.md)\n\n## 메타"
        ));
        assert!(content.contains("source_count: 1"));
    }

    /// `source_count` is re-derived, not merely kept consistent with the section beside it.
    /// A page whose entries are already right but whose count is wrong — a hand edit, a run
    /// that died between the two writes — is exactly the drift this command exists to
    /// repair, and it is the one shape that looks unchanged if the two facts are checked as
    /// alternatives rather than together.
    #[test]
    fn a_correct_source_list_with_a_wrong_count_is_still_repaired() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("wiki/concepts/oy365.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "---\nid: oy365\nsource_count: 7\n---\n\n# oy365\n\n## 출처\n\n- [daily/slack/2026-05-20](../../daily/slack/2026-05-20.md)\n\n## 메타\n\n- key: value\n",
        )
        .unwrap();

        let pages = vec![
            build_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            build_page(
                "daily/slack/2026-05-20",
                "daily/slack/2026-05-20.md",
                &["wiki/concepts/oy365"],
            ),
        ];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.unchanged, 0, "a wrong count is not 'unchanged'");
        assert_eq!(report.updated.len(), 1);
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("source_count: 1"), "{content}");
    }

    #[test]
    fn removes_stale_backlink() {
        let dir = TempDir::new().unwrap();
        // Disk says the concept is referenced by an old daily page that no longer
        // links to it.
        write_concept(&dir, "oy365", &["- [old](../../daily/slack/2026-01-01.md)"]);

        let pages = vec![build_page(
            "wiki/concepts/oy365",
            "wiki/concepts/oy365.md",
            &[],
        )];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 1);
        assert!(report.updated[0].added.is_empty());
        assert_eq!(report.updated[0].removed, vec!["daily/slack/2026-01-01"]);

        let content = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();
        // Body collapsed to empty — section heading remains, no list items.
        assert!(content.contains("## 출처\n\n\n## 메타"));
    }

    #[test]
    fn preserves_other_sections() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("wiki/concepts/oy365.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "---\nid: oy365\n---\n\n# oy365\n\n## 핵심\n\nThis is the synthesis paragraph.\n\n## 출처\n\n- [old](../../daily/x/old.md)\n\n## 메타\n\n- references: 1\n",
        )
        .unwrap();

        let pages = vec![
            build_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            build_page(
                "daily/x/2026-05-20",
                "daily/x/2026-05-20.md",
                &["wiki/concepts/oy365"],
            ),
        ];

        sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
            .unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("## 핵심\n\nThis is the synthesis paragraph."));
        assert!(content.contains("## 메타\n\n- references: 1"));
        assert!(content.contains("## 출처\n\n- [daily/x/2026-05-20](../../daily/x/2026-05-20.md)"));
        assert!(!content.contains("(../../daily/x/old.md)"));
    }

    #[test]
    fn dry_run_does_not_write() {
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);
        let before = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();

        let pages = vec![
            build_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            build_page(
                "daily/x/2026-05-20",
                "daily/x/2026-05-20.md",
                &["wiki/concepts/oy365"],
            ),
        ];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, true, &VaultDirs::default())
                .unwrap();
        assert!(report.dry_run);
        assert_eq!(report.updated.len(), 1);

        let after = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();
        assert_eq!(before, after, "dry-run must not write");
    }

    #[test]
    fn idempotent_on_second_run() {
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);

        let pages = vec![
            build_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            build_page(
                "daily/x/2026-05-20",
                "daily/x/2026-05-20.md",
                &["wiki/concepts/oy365"],
            ),
        ];

        // First run rewrites the page.
        let first =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(first.updated.len(), 1);

        // Second run: every concept page is already in sync.
        let second =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert!(second.updated.is_empty());
        assert_eq!(second.unchanged, 1);
    }

    #[test]
    fn english_locale_uses_sources_heading() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("wiki/concepts/oy365.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "---\nid: oy365\n---\n\n# oy365\n\n## Sources\n\n\n## Metadata\n",
        )
        .unwrap();

        let pages = vec![
            build_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            build_page(
                "daily/x/2026-05-20",
                "daily/x/2026-05-20.md",
                &["wiki/concepts/oy365"],
            ),
        ];

        sync_concept_backlinks(&pages, dir.path(), Locale::En, false, &VaultDirs::default())
            .unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains(
            "## Sources\n\n- [daily/x/2026-05-20](../../daily/x/2026-05-20.md)\n\n## Metadata"
        ));
    }

    #[test]
    fn self_link_to_concept_is_ignored() {
        // A concept page that links itself should not list itself as a source.
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);

        let pages = vec![build_page(
            "wiki/concepts/oy365",
            "wiki/concepts/oy365.md",
            &["wiki/concepts/oy365"],
        )];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 0);
        assert_eq!(report.unchanged, 1);
    }

    #[test]
    fn concept_to_concept_link_is_not_a_source() {
        // Only content pages qualify as sources; a citation from another concept
        // belongs in `## Related` and must not be credited here.
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "target", &[]);
        write_concept(&dir, "citer", &[]);

        let pages = vec![
            build_page("wiki/concepts/target", "wiki/concepts/target.md", &[]),
            build_page(
                "wiki/concepts/citer",
                "wiki/concepts/citer.md",
                &["wiki/concepts/target"],
            ),
        ];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert!(report.updated.is_empty());
    }
}
