//! Re-derive each concept page's `## <Sources>` body AND its frontmatter
//! `source_count` from the actual wikilink graph — this module is the single
//! source-of-truth for both. Ingest writes neither: it renders the Sources heading
//! empty and preserves the on-disk `source_count` verbatim (0 for a new page), so this
//! sync is what makes them correct: every daily/work-log/etc. page that wikilinks the concept
//! becomes a `- [[…]]` entry, and the count is that entry total. Manual edits (a daily
//! page gains/loses a `[[concept]]` link) and source-page deletions are reflected on
//! the next run.
//!
//! Pure set comparison: no heuristics, no LLM, no per-source rules. A page is in
//! the sources list iff it has an outgoing wikilink whose target resolves to that
//! concept's filename.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::path::{Path, PathBuf};

use lk_core::concept::slugify;
use lk_core::config::VaultDirs;
use lk_core::frontmatter;
use lk_core::i18n::Locale;
use lk_vault::{VaultWriter, replace_section, section_body, set_frontmatter_field};
use serde::Serialize;

use crate::GraphError;
use crate::scan::{ScannedPage, is_concept_page, is_valid_source};

/// Outcome of one concept page's reconciliation.
#[derive(Debug, Clone, Serialize)]
pub struct ConceptUpdate {
    /// Vault-relative path of the concept page that was (or would be) updated.
    pub path: PathBuf,
    /// Sources that were missing from the page and would be added.
    pub added: Vec<String>,
    /// Sources that were on the page but no longer have an incoming wikilink.
    pub removed: Vec<String>,
}

/// Outcome of a backlinks-sync run (a mutating operation), mirroring `MergeResult`:
/// domain-module operation outcomes are `*Result`; the CLI presentation wrapper is
/// `output::BacklinksSyncReport`.
#[derive(Debug, Default, Serialize)]
pub struct BacklinksSyncResult {
    /// Concept pages whose sources section differed and was rewritten (or would be,
    /// under `--dry-run`).
    pub updated: Vec<ConceptUpdate>,
    /// Count of concept pages whose existing sources section was already correct.
    pub unchanged: usize,
    /// Whether this was a dry run (no writes were performed).
    pub dry_run: bool,
}

/// Recompute the `## <Sources>` section on every `{wiki}/concepts/{slug}.md` page from
/// the incoming wikilinks observed in `pages`, and rewrite any page whose section
/// differs. Returns the diff per page plus a count of pages that needed no change.
///
/// `dry_run = true` skips all writes but still reports what would change. Re-running
/// the command after a real run is a no-op: the sources block is generated by the
/// same routine that compares against it.
pub fn sync_concept_backlinks(
    pages: &[ScannedPage],
    vault_root: &Path,
    locale: Locale,
    dry_run: bool,
    dirs: &VaultDirs,
) -> Result<BacklinksSyncResult, GraphError> {
    // Reverse index: concept slug (filename) → sorted set of source page ids that
    // wikilink to it. Use BTreeMap/BTreeSet so the rendered body is deterministic.
    //
    // Only event/document pages are considered sources — concept-to-concept links
    // belong in `## Related`, not `## Sources`, and navigation pages
    // (`wiki/index.md`, `wiki/AGENTS.md`) shouldn't appear as sources at all.
    // Map each concept's declared alias slugs to its canonical filename slug so a bare
    // `[[synonym]]` citation is credited to the concept — keeping `source_count` and
    // `## Sources` consistent with the wikilink graph's alias resolution. The exclusion
    // set is EVERY real page's filename slug (not just concepts): an alias that collides
    // with any real page is inert because the real page wins in `VaultExistence` /
    // `WikiGraph`, so crediting it here would diverge from the graph. The first concept
    // to claim a free alias wins (same precedence as `VaultExistence`).
    let real_slugs: HashSet<String> = pages
        .iter()
        .filter_map(|p| {
            p.path
                .file_stem()
                .and_then(|s| s.to_str())
                .and_then(slugify)
        })
        .collect();
    // alias → (winning concept id, that concept's stem). When two concepts claim the
    // same alias the winner is the concept with the smallest id — the SAME tiebreak
    // `VaultExistence::by_alias` uses — so a duplicate alias credits the exact concept
    // the graph resolves it to, regardless of page order or concept-file nesting.
    let mut alias_winner: HashMap<String, (String, String)> = HashMap::new();
    for page in pages {
        if !is_concept_page(&page.path, dirs) {
            continue;
        }
        let Some(stem) = page
            .path
            .file_stem()
            .and_then(|s| s.to_str())
            .and_then(slugify)
        else {
            continue;
        };
        for alias in &page.aliases {
            if real_slugs.contains(alias) {
                continue;
            }
            alias_winner
                .entry(alias.clone())
                .and_modify(|(cur_id, cur_stem)| {
                    if page.id < *cur_id {
                        *cur_id = page.id.clone();
                        *cur_stem = stem.clone();
                    }
                })
                .or_insert_with(|| (page.id.clone(), stem.clone()));
        }
    }
    let alias_to_stem: HashMap<String, String> = alias_winner
        .into_iter()
        .map(|(alias, (_, stem))| (alias, stem))
        .collect();

    let mut incoming: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for page in pages {
        if !is_valid_source(&page.path, dirs) {
            continue;
        }
        for target in &page.outgoing {
            // Credit an alias citation to the concept's canonical slug.
            let key = alias_to_stem
                .get(target)
                .cloned()
                .unwrap_or_else(|| target.clone());
            incoming.entry(key).or_default().insert(page.id.clone());
        }
    }

    let writer = VaultWriter::new(vault_root);
    let mut report = BacklinksSyncResult {
        dry_run,
        ..BacklinksSyncResult::default()
    };

    for page in pages {
        if !is_concept_page(&page.path, dirs) {
            continue;
        }

        let stem = page
            .path
            .file_stem()
            .and_then(|s| s.to_str())
            .and_then(slugify)
            .unwrap_or_default();
        if stem.is_empty() {
            continue;
        }

        // Sources for this concept = every page whose outgoing wikilinks include
        // this concept's filename slug. Self-references are excluded for the same
        // reason the graph excludes self-edges.
        let mut sources: Vec<String> = incoming
            .get(&stem)
            .map(|set| {
                set.iter()
                    .filter(|id| id.as_str() != page.id)
                    .cloned()
                    .collect()
            })
            .unwrap_or_default();
        sources.sort();

        let full_path = vault_root.join(&page.path);
        let raw = std::fs::read_to_string(&full_path)
            .map_err(|e| GraphError::Io(format!("failed to read {}: {e}", full_path.display())))?;

        // Find the existing Sources heading under ANY locale (a page authored before a
        // `vault.locale` switch keeps its old-language heading), then rewrite under it —
        // mirrors the pipeline's all-locale `capture_section`. New pages with no such
        // section fall back to the current locale's heading.
        let heading = Locale::ALL
            .iter()
            .map(|l| l.strings().concept_sources)
            .find(|h| section_body(&raw, h).is_some())
            .unwrap_or_else(|| locale.strings().concept_sources);

        let existing = parse_existing_sources(&raw, heading);
        let existing_set: BTreeSet<&str> = existing.iter().map(String::as_str).collect();
        let desired_set: BTreeSet<&str> = sources.iter().map(String::as_str).collect();

        // `source_count` frontmatter is re-derived here too (ingest preserves the
        // on-disk value but never computes it): the authoritative count is the number
        // of incoming citations, the same set that drives the `## Sources` body.
        let existing_count = frontmatter::parse_page(&raw)
            .ok()
            .and_then(|p| p.frontmatter.get("source_count").and_then(|v| v.as_u64()))
            .unwrap_or(0);
        let desired_count = sources.len() as u64;

        if existing_set == desired_set && existing_count == desired_count {
            report.unchanged += 1;
            continue;
        }

        let added: Vec<String> = desired_set
            .difference(&existing_set)
            .map(|s| (*s).to_owned())
            .collect();
        let removed: Vec<String> = existing_set
            .difference(&desired_set)
            .map(|s| (*s).to_owned())
            .collect();

        let new_body = render_sources_body(&sources);
        let updated_content =
            set_source_count(&replace_section(&raw, heading, &new_body), desired_count);

        if !dry_run && updated_content != raw {
            writer
                .write_page_sync(&page.path, &updated_content)
                .map_err(|e| {
                    GraphError::Io(format!("failed to write {}: {e}", page.path.display()))
                })?;
        }

        report.updated.push(ConceptUpdate {
            path: page.path.clone(),
            added,
            removed,
        });
    }

    Ok(report)
}

/// Extract `[[…]]` targets from the existing `## <heading>` section, in their
/// on-disk order. Used only to compute the diff (added/removed) — the rewritten
/// body is canonicalised through [`render_sources_body`].
pub(crate) fn parse_existing_sources(content: &str, heading: &str) -> Vec<String> {
    let target = format!("## {heading}");
    let lines: Vec<&str> = content.split_inclusive('\n').collect();

    let Some(start) = lines.iter().position(|l| {
        let stripped = l.strip_suffix('\n').unwrap_or(l);
        stripped == target
    }) else {
        return Vec::new();
    };

    let end = lines[start + 1..]
        .iter()
        .position(|l| {
            let stripped = l.strip_suffix('\n').unwrap_or(l);
            stripped.starts_with("## ")
        })
        .map(|rel| rel + start + 1)
        .unwrap_or(lines.len());

    let mut out = Vec::new();
    for raw in &lines[start + 1..end] {
        let line = raw.strip_suffix('\n').unwrap_or(raw).trim();
        // Match `- [[target]]` (Obsidian wikilink list item). Anchors / aliases
        // are stripped so `- [[foo#bar|label]]` and `- [[foo]]` both report `foo`.
        let Some(rest) = line.strip_prefix("- [[") else {
            continue;
        };
        let Some(inner) = rest.strip_suffix("]]") else {
            continue;
        };
        // Page part only (drop anchor/alias) via the single-sourced wikilink parser.
        let (page, _anchor, _alias) = lk_core::wikilink::split_wikilink_parts(inner);
        let target = page.trim();
        if !target.is_empty() {
            out.push(target.to_owned());
        }
    }
    out
}

/// Set the frontmatter `source_count` — a thin wrapper over the single-sourced
/// `set_frontmatter_field` so backlinks and the audit marker share one writer.
fn set_source_count(content: &str, count: u64) -> String {
    set_frontmatter_field(content, "source_count", &count.to_string())
}

/// Render the sources list to the same shape `concept.md.jinja` produces:
/// `- [[id]]` per line, newline-separated, no trailing newline (the section
/// helper owns separators).
pub(crate) fn render_sources_body(sources: &[String]) -> String {
    sources
        .iter()
        .map(|s| format!("- [[{s}]]"))
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_page(id: &str, rel: &str, outgoing: &[&str]) -> ScannedPage {
        ScannedPage {
            id: id.to_owned(),
            path: PathBuf::from(rel),
            title: id.to_owned(),
            outgoing: outgoing.iter().map(|s| (*s).to_string()).collect(),
            aliases: Vec::new(),
        }
    }

    fn write_concept(dir: &TempDir, stem: &str, sources: &[&str]) {
        let path = dir.path().join("wiki/concepts").join(format!("{stem}.md"));
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let count = sources.len();
        let body = if sources.is_empty() {
            format!(
                "---\nid: {stem}\nsource_count: {count}\n---\n\n# {stem}\n\n## 출처\n\n\n## 메타\n\n- key: value\n"
            )
        } else {
            let lines: Vec<String> = sources.iter().map(|s| format!("- [[{s}]]")).collect();
            format!(
                "---\nid: {stem}\nsource_count: {count}\n---\n\n# {stem}\n\n## 출처\n\n{}\n\n## 메타\n\n- key: value\n",
                lines.join("\n")
            )
        };
        std::fs::write(&path, body).unwrap();
    }

    #[test]
    fn inserts_missing_backlink() {
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);

        let pages = vec![
            make_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            // A daily page that wikilinks the concept.
            make_page(
                "daily/slack/2026-05-20",
                "daily/slack/2026-05-20.md",
                &["oy365"],
            ),
        ];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 1);
        assert_eq!(report.unchanged, 0);
        assert_eq!(report.updated[0].added, vec!["daily/slack/2026-05-20"]);
        assert!(report.updated[0].removed.is_empty());

        let content = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();
        assert!(content.contains("## 출처\n\n- [[daily/slack/2026-05-20]]\n\n## 메타"));
    }

    #[test]
    fn alias_citation_is_credited_to_the_concept() {
        // A daily page citing `[[k8s]]` (an alias of the kubernetes concept) must be
        // listed under that concept's `## Sources` and counted, exactly as a citation
        // by its canonical slug would — keeping source_count consistent with the graph.
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "kubernetes", &[]);
        let pages = vec![
            ScannedPage {
                id: "wiki/concepts/kubernetes".to_owned(),
                path: PathBuf::from("wiki/concepts/kubernetes.md"),
                title: "kubernetes".to_owned(),
                outgoing: vec![],
                aliases: vec!["k8s".to_owned()],
            },
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["k8s"]),
        ];
        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 1);
        assert_eq!(report.updated[0].added, vec!["daily/x/2026-05-20"]);
        let content =
            std::fs::read_to_string(dir.path().join("wiki/concepts/kubernetes.md")).unwrap();
        assert!(content.contains("## 출처\n\n- [[daily/x/2026-05-20]]"));
        assert!(content.contains("source_count: 1"));
    }

    #[test]
    fn duplicate_alias_credits_smallest_id_concept_not_smallest_stem() {
        // Two concepts in different subdirectories claim the same alias. The winner must
        // be the smallest *id* (matching VaultExistence's resolver), NOT the smallest stem.
        // Here id order and stem order disagree, so this distinguishes the two tiebreaks
        // and locks the resolvers to a single shared key.
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "aaa/banana", &[]); // smaller id, larger stem
        write_concept(&dir, "zzz/apple", &[]); // larger id, smaller stem
        let pages = vec![
            ScannedPage {
                id: "wiki/concepts/zzz/apple".to_owned(),
                path: PathBuf::from("wiki/concepts/zzz/apple.md"),
                title: "apple".to_owned(),
                outgoing: vec![],
                aliases: vec!["fruit".to_owned()],
            },
            ScannedPage {
                id: "wiki/concepts/aaa/banana".to_owned(),
                path: PathBuf::from("wiki/concepts/aaa/banana.md"),
                title: "banana".to_owned(),
                outgoing: vec![],
                aliases: vec!["fruit".to_owned()],
            },
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["fruit"]),
        ];
        sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
            .unwrap();
        let banana =
            std::fs::read_to_string(dir.path().join("wiki/concepts/aaa/banana.md")).unwrap();
        assert!(
            banana.contains("- [[daily/x/2026-05-20]]"),
            "the smallest-id concept must be credited the alias citation"
        );
        let apple = std::fs::read_to_string(dir.path().join("wiki/concepts/zzz/apple.md")).unwrap();
        assert!(
            !apple.contains("- [[daily/x/2026-05-20]]"),
            "the smaller-stem (larger-id) concept must NOT be credited"
        );
    }

    #[test]
    fn alias_colliding_with_a_real_page_slug_is_not_credited() {
        // `kubernetes` declares the alias `helm`, but a real `helm` document exists.
        // A bare `[[helm]]` resolves to the document in the graph (a real page beats an
        // alias), so backlinks must NOT credit it to kubernetes — otherwise source_count
        // would diverge from the wikilink graph.
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "kubernetes", &[]);
        let pages = vec![
            ScannedPage {
                id: "wiki/concepts/kubernetes".to_owned(),
                path: PathBuf::from("wiki/concepts/kubernetes.md"),
                title: "kubernetes".to_owned(),
                outgoing: vec![],
                aliases: vec!["helm".to_owned()],
            },
            make_page("wiki/documents/helm", "wiki/documents/helm.md", &[]),
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["helm"]),
        ];
        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        // kubernetes is already in sync with zero sources — the `[[helm]]` citation is
        // not credited to it.
        assert!(
            report.updated.is_empty(),
            "alias colliding with a real page slug must not be credited: {report:?}"
        );
        assert_eq!(report.unchanged, 1);
    }

    #[test]
    fn removes_stale_backlink() {
        let dir = TempDir::new().unwrap();
        // Disk says the concept is referenced by an old daily page that no longer
        // links to it.
        write_concept(&dir, "oy365", &["daily/slack/2026-01-01"]);

        let pages = vec![make_page(
            "wiki/concepts/oy365",
            "wiki/concepts/oy365.md",
            &[],
        )];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 1);
        assert!(report.updated[0].added.is_empty());
        assert_eq!(report.updated[0].removed, vec!["daily/slack/2026-01-01"]);

        let content = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();
        // Body collapsed to empty — section heading remains, no `- [[…]]` lines.
        assert!(content.contains("## 출처\n\n\n## 메타"));
    }

    #[test]
    fn preserves_other_sections() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("wiki/concepts/oy365.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "---\nid: oy365\n---\n\n# oy365\n\n## 핵심\n\nThis is the synthesis paragraph.\n\n## 출처\n\n- [[old]]\n\n## 메타\n\n- references: 1\n",
        )
        .unwrap();

        let pages = vec![
            make_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["oy365"]),
        ];

        sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
            .unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("## 핵심\n\nThis is the synthesis paragraph."));
        assert!(content.contains("## 메타\n\n- references: 1"));
        assert!(content.contains("## 출처\n\n- [[daily/x/2026-05-20]]"));
        assert!(!content.contains("- [[old]]"));
    }

    #[test]
    fn dry_run_does_not_write() {
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);
        let before = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();

        let pages = vec![
            make_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["oy365"]),
        ];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, true, &VaultDirs::default())
                .unwrap();
        assert!(report.dry_run);
        assert_eq!(report.updated.len(), 1);

        let after = std::fs::read_to_string(dir.path().join("wiki/concepts/oy365.md")).unwrap();
        assert_eq!(before, after, "dry-run must not write");
    }

    #[test]
    fn idempotent_on_second_run() {
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);

        let pages = vec![
            make_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["oy365"]),
        ];

        // First run rewrites the page.
        let first =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(first.updated.len(), 1);

        // Second run: every concept page is already in sync.
        let second =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert!(second.updated.is_empty());
        assert_eq!(second.unchanged, 1);
    }

    #[test]
    fn english_locale_uses_sources_heading() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("wiki/concepts/oy365.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "---\nid: oy365\n---\n\n# oy365\n\n## Sources\n\n\n## Metadata\n",
        )
        .unwrap();

        let pages = vec![
            make_page("wiki/concepts/oy365", "wiki/concepts/oy365.md", &[]),
            make_page("daily/x/2026-05-20", "daily/x/2026-05-20.md", &["oy365"]),
        ];

        sync_concept_backlinks(&pages, dir.path(), Locale::En, false, &VaultDirs::default())
            .unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("## Sources\n\n- [[daily/x/2026-05-20]]\n\n## Metadata"));
    }

    #[test]
    fn self_link_to_concept_is_ignored() {
        // A concept page that wikilinks itself should not list itself as a source.
        let dir = TempDir::new().unwrap();
        write_concept(&dir, "oy365", &[]);

        let pages = vec![make_page(
            "wiki/concepts/oy365",
            "wiki/concepts/oy365.md",
            &["oy365"],
        )];

        let report =
            sync_concept_backlinks(&pages, dir.path(), Locale::Ko, false, &VaultDirs::default())
                .unwrap();
        assert_eq!(report.updated.len(), 0);
        assert_eq!(report.unchanged, 1);
    }
}
